/**
 * Evaluator types.
 *
 * The evaluator takes TypeScript source text produced by the SDK emitter (or
 * hand-authored by the user / generated by the chat assistant) and returns a
 * structured flow definition — nodes + edges + metadata. Input sources
 * typically look like:
 *
 *   import { defineFlow, input, code, output } from '@invect/sdk';
 *   import { gmailSendMessageAction } from '@invect/actions/gmail';
 *
 *   export default defineFlow({ nodes: [...], edges: [...] });
 *
 * The evaluator enforces a module-import allowlist — `@invect/sdk` (and
 * subpaths), `@invect/actions/*`, and any extra modules the caller explicitly
 * registers via `additionalModules`. Everything else (node builtins, user
 * filesystem paths, network fetches) is blocked via a pre-eval source scan.
 */

import type { ResolvedEdge, SdkFlowNode } from '../types';

export interface EvaluatorOptions {
  /**
   * Additional modules to expose to the evaluated source. Useful when the
   * source imports user-registered custom actions from the caller's own repo.
   * Keys are import specifiers; values are the module objects.
   */
  additionalModules?: Record<string, unknown>;

  /**
   * Additional import specifiers to allow without providing a module. Useful
   * when the import target is resolvable via Node's own resolution (e.g. a
   * globally-installed action package). Defaults to `[]`.
   */
  additionalAllowedImports?: string[];

  /**
   * Max time in milliseconds the evaluation may take before it is aborted.
   * Defaults to 10_000. Does NOT interrupt synchronous infinite loops (that
   * needs a Worker — future enhancement).
   */
  timeoutMs?: number;

  /**
   * Optional import specifier that resolves the `@invect/sdk` itself. Tests
   * pin this to the live workspace path; production callers should leave it
   * unset (defaults to `@invect/sdk`).
   */
  sdkImportSpecifier?: string;
}

export interface EvaluatedFlow {
  /** The flow's exported nodes after `defineFlow` ran. */
  nodes: SdkFlowNode[];
  /** Edges normalised by `defineFlow` (tuple → object form). */
  edges: ResolvedEdge[];
  /** Flow metadata (name/description/tags), if set by the source. */
  metadata?: { name?: string; description?: string; tags?: string[] };
}

export type EvaluatorErrorCode =
  | 'import-forbidden'
  | 'import-parse-failed'
  | 'dynamic-import'
  | 'eval-failed'
  | 'no-default-export'
  | 'default-export-not-a-flow'
  | 'timeout';

export interface EvaluatorError {
  code: EvaluatorErrorCode;
  message: string;
  /** The offending import specifier, when applicable. */
  specifier?: string;
  /** Optional line number within the source text. */
  line?: number;
}

export interface EvaluatorResult {
  /** The evaluated flow, if evaluation succeeded. */
  flow: EvaluatedFlow | null;
  /** Any errors that prevented a successful evaluation. */
  errors: EvaluatorError[];
  /** True when `flow` is non-null. */
  ok: boolean;
}
