export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'core',
        'express',
        'nestjs',
        'nextjs',
        'ui',
        'cli',
        'layouts',
        'auth',
        'rbac',
        'webhooks',
        'version-control',
        'cloudflare-agents',
        'mcp',
        'docs',
        'deps',
      ],
    ],
    'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
    'body-max-line-length': [1, 'always', 200],
  },
};
