packages:
  - pkg/*
  - pkg/plugins/*
  - examples/*
  - experiments/*
  - docs

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - prisma
  - sharp
  - sqlite3
  - unrs-resolver
