/**
 * Re-exports provider definitions from `@invect/actions`.
 *
 * Uses explicit named re-exports so tsdown emits value exports in the
 * declaration bundle (a bare `export *` collapses to a type-only namespace
 * alias and the providers would lose their value binding in `@invect/core`'s
 * public dist).
 */

export {
  CORE_PROVIDER,
  HTTP_PROVIDER,
  GMAIL_PROVIDER,
  SLACK_PROVIDER,
  GITHUB_PROVIDER,
  GOOGLE_DOCS_PROVIDER,
  GOOGLE_SHEETS_PROVIDER,
  GOOGLE_DRIVE_PROVIDER,
  GOOGLE_CALENDAR_PROVIDER,
  LINEAR_PROVIDER,
  POSTGRES_PROVIDER,
  TRIGGERS_PROVIDER,
  MICROSOFT_PROVIDER,
  MICROSOFT_TEAMS_PROVIDER,
  SENTRY_PROVIDER,
  GRAFANA_PROVIDER,
  SALESFORCE_PROVIDER,
  HUBSPOT_PROVIDER,
  JIRA_PROVIDER,
  ASANA_PROVIDER,
  TRELLO_PROVIDER,
  DROPBOX_PROVIDER,
  ONEDRIVE_PROVIDER,
  STRIPE_PROVIDER,
  TWITTER_PROVIDER,
  LINKEDIN_PROVIDER,
  FACEBOOK_PROVIDER,
  SHOPIFY_PROVIDER,
  WOOCOMMERCE_PROVIDER,
  ZENDESK_PROVIDER,
  INTERCOM_PROVIDER,
  FRESHDESK_PROVIDER,
  SEGMENT_PROVIDER,
  MIXPANEL_PROVIDER,
  GOOGLE_ANALYTICS_PROVIDER,
  GITLAB_PROVIDER,
  RESEND_PROVIDER,
  SENDGRID_PROVIDER,
  NOTION_PROVIDER,
  CLOUDWATCH_PROVIDER,
  PAGERDUTY_PROVIDER,
} from '@invect/actions/providers';
