import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/providers.ts',
    'src/registry/index.ts',
    'src/core/index.ts',
    'src/asana/index.ts',
    'src/cloudwatch/index.ts',
    'src/dropbox/index.ts',
    'src/facebook/index.ts',
    'src/freshdesk/index.ts',
    'src/github/index.ts',
    'src/gitlab/index.ts',
    'src/gmail/index.ts',
    'src/http/index.ts',
    'src/google-analytics/index.ts',
    'src/google-calendar/index.ts',
    'src/google-docs/index.ts',
    'src/google-drive/index.ts',
    'src/google-sheets/index.ts',
    'src/grafana/index.ts',
    'src/hubspot/index.ts',
    'src/intercom/index.ts',
    'src/jira/index.ts',
    'src/linear/index.ts',
    'src/linkedin/index.ts',
    'src/microsoft/index.ts',
    'src/microsoft-teams/index.ts',
    'src/mixpanel/index.ts',
    'src/notion/index.ts',
    'src/onedrive/index.ts',
    'src/pagerduty/index.ts',
    'src/postgres/index.ts',
    'src/resend/index.ts',
    'src/salesforce/index.ts',
    'src/segment/index.ts',
    'src/sendgrid/index.ts',
    'src/sentry/index.ts',
    'src/shopify/index.ts',
    'src/slack/index.ts',
    'src/stripe/index.ts',
    'src/trello/index.ts',
    'src/triggers/index.ts',
    'src/twitter/index.ts',
    'src/woocommerce/index.ts',
    'src/zendesk/index.ts',
  ],
  format: ['esm', 'cjs'],
  dts: { resolve: false },
  sourcemap: true,
  clean: true,
  deps: {
    neverBundle: ['zod', '@invect/action-kit'],
  },
  outExtensions({ format }) {
    return { js: format === 'cjs' ? '.cjs' : '.mjs' };
  },
});
