import {
  sqliteTable,
  text,
  integer,
  primaryKey,
  type AnySQLiteColumn,
} from 'drizzle-orm/sqlite-core';
import { relations, sql } from 'drizzle-orm';
import { randomUUID } from 'crypto';
import { BatchStatus, FlowRunStatus, NodeExecutionStatus } from '@invect/core';
import type {
  BatchProvider,
  CredentialAuthType,
  CredentialConfig,
  CredentialType,
  InvectDefinitionRuntime,
  JSONValue,
  TriggerType,
} from '@invect/core/types';

// =============================================================================
// Invect tables — AUTO-GENERATED by @invect/cli
// Do not edit below this line. Run `npx invect-cli generate` to regenerate.
// =============================================================================

type FlowAccessPermission = string;

export const user = sqliteTable('user', {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: integer('email_verified', { mode: 'boolean' }).notNull().default(false),
  image: text('image'),
  role: text('role').default('default'),
  banned: integer('banned', { mode: 'boolean' }).default(false),
  banReason: text('ban_reason'),
  banExpires: text('ban_expires'),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const account = sqliteTable('account', {
  id: text('id').primaryKey().notNull(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: text('access_token_expires_at'),
  refreshTokenExpiresAt: text('refresh_token_expires_at'),
  scope: text('scope'),
  password: text('password'),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const session = sqliteTable('session', {
  id: text('id').primaryKey().notNull(),
  expiresAt: text('expires_at').notNull(),
  token: text('token').notNull().unique(),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  impersonatedBy: text('impersonated_by'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
});

export const verification = sqliteTable('verification', {
  id: text('id').primaryKey().notNull(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: text('expires_at').notNull(),
  createdAt: text('created_at'),
  updatedAt: text('updated_at'),
});

export const flowAccess = sqliteTable('flow_access', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  flowId: text('flow_id')
    .notNull()
    .references(() => flows.id, { onDelete: 'cascade' }),
  userId: text('user_id'),
  teamId: text('team_id'),
  permission: text('permission').notNull().default('viewer'),
  grantedBy: text('granted_by'),
  grantedAt: text('granted_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  expiresAt: text('expires_at'),
});

export const credentials = sqliteTable('credentials', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  name: text('name').notNull(),
  type: text('type').$type<CredentialType>().notNull(),
  authType: text('auth_type').$type<CredentialAuthType>().notNull(),
  config: text('config', { mode: 'json' }).$type<CredentialConfig>().notNull(),
  description: text('description'),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  workspaceId: text('workspace_id'),
  isShared: integer('is_shared', { mode: 'boolean' }).notNull().default(false),
  metadata: text('metadata', { mode: 'json' }).$type<Record<string, unknown>>(),
  lastUsedAt: text('last_used_at'),
  expiresAt: text('expires_at'),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const flows = sqliteTable('flows', {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  description: text('description'),
  tags: text('tags', { mode: 'json' }).$type<string[]>(),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  liveVersionNumber: integer('live_version_number'),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  scope_id: text('scope_id').references(() => rbac_teams.id, { onDelete: 'set null' }),
});

export const flowTriggers = sqliteTable('flow_triggers', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  flowId: text('flow_id')
    .notNull()
    .references(() => flows.id, { onDelete: 'cascade' }),
  nodeId: text('node_id').notNull(),
  type: text('type').$type<TriggerType>().notNull(),
  isEnabled: integer('is_enabled', { mode: 'boolean' }).notNull().default(true),
  webhookPath: text('webhook_path').unique(),
  webhookSecret: text('webhook_secret'),
  cronExpression: text('cron_expression'),
  cronTimezone: text('cron_timezone'),
  lastTriggeredAt: text('last_triggered_at'),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const flowVersions = sqliteTable(
  'flow_versions',
  {
    flowId: text('flow_id')
      .notNull()
      .references(() => flows.id, { onDelete: 'cascade' }),
    version: integer('version').notNull(),
    invectDefinition: text('invect_definition', { mode: 'json' })
      .$type<InvectDefinitionRuntime>()
      .notNull(),
    createdAt: text('created_at')
      .notNull()
      .default(sql`CURRENT_TIMESTAMP`),
    createdBy: text('created_by'),
  },
  (table) => [primaryKey({ columns: [table.version, table.flowId] })],
);

export const chatMessages = sqliteTable('chat_messages', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  flowId: text('flow_id')
    .notNull()
    .references(() => flows.id, { onDelete: 'cascade' }),
  role: text('role').$type<'user' | 'assistant' | 'system' | 'tool'>().notNull(),
  content: text('content').notNull().default(''),
  toolMeta: text('tool_meta', { mode: 'json' }).$type<Record<string, unknown>>(),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const flowRuns = sqliteTable('flow_executions', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  flowId: text('flow_id')
    .notNull()
    .references(() => flows.id, { onDelete: 'cascade' }),
  flowVersion: integer('flow_version').notNull(),
  status: text('status').$type<FlowRunStatus>().notNull().default(FlowRunStatus.PENDING),
  inputs: text('inputs', { mode: 'json' }).$type<JSONValue>().notNull(),
  outputs: text('outputs', { mode: 'json' }).$type<JSONValue>(),
  error: text('error'),
  startedAt: text('started_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  completedAt: text('completed_at'),
  duration: integer('duration'),
  createdBy: text('created_by'),
  triggerType: text('trigger_type'),
  triggerId: text('trigger_id'),
  triggerNodeId: text('trigger_node_id'),
  triggerData: text('trigger_data', { mode: 'json' }).$type<JSONValue>(),
  lastHeartbeatAt: text('last_heartbeat_at'),
});

export const actionTraces = sqliteTable('action_traces', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  flowRunId: text('flow_run_id')
    .notNull()
    .references(() => flowRuns.id, { onDelete: 'cascade' }),
  parentNodeExecutionId: text('parent_node_execution_id').references(
    (): AnySQLiteColumn => actionTraces.id,
    { onDelete: 'cascade' },
  ),
  nodeId: text('node_id'),
  nodeType: text('node_type'),
  toolId: text('tool_id'),
  toolName: text('tool_name'),
  iteration: integer('iteration'),
  status: text('status')
    .$type<NodeExecutionStatus>()
    .notNull()
    .default(NodeExecutionStatus.PENDING),
  inputs: text('inputs', { mode: 'json' }).$type<JSONValue>().notNull(),
  outputs: text('outputs', { mode: 'json' }).$type<JSONValue>(),
  error: text('error'),
  startedAt: text('started_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  completedAt: text('completed_at'),
  duration: integer('duration'),
  retryCount: integer('retry_count').notNull().default(0),
});

export const batchJobs = sqliteTable('batch_jobs', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  flowRunId: text('flow_run_id')
    .notNull()
    .references(() => flowRuns.id, { onDelete: 'cascade' }),
  nodeId: text('node_id').notNull(),
  provider: text('provider').$type<BatchProvider>().notNull(),
  batchId: text('batch_id'),
  status: text('status').$type<BatchStatus>().notNull().default(BatchStatus.SUBMITTED),
  requestData: text('request_data', { mode: 'json' }).notNull(),
  responseData: text('response_data', { mode: 'json' }),
  error: text('error'),
  submittedAt: text('submitted_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  completedAt: text('completed_at'),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const rbac_scope_access = sqliteTable('rbac_scope_access', {
  id: text('id').primaryKey().notNull(),
  scope_id: text('scope_id')
    .notNull()
    .references(() => rbac_teams.id, { onDelete: 'cascade' }),
  user_id: text('user_id'),
  team_id: text('team_id'),
  permission: text('permission').$type<FlowAccessPermission>().notNull().default('viewer'),
  granted_by: text('granted_by'),
  granted_at: text('granted_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const rbac_team_members = sqliteTable('rbac_team_members', {
  id: text('id').primaryKey().notNull(),
  team_id: text('team_id')
    .notNull()
    .references(() => rbac_teams.id, { onDelete: 'cascade' }),
  user_id: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  created_at: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const rbac_teams = sqliteTable('rbac_teams', {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  description: text('description'),
  parent_id: text('parent_id').references((): AnySQLiteColumn => rbac_teams.id, {
    onDelete: 'set null',
  }),
  created_by: text('created_by').references(() => user.id, { onDelete: 'no action' }),
  created_at: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updated_at: text('updated_at'),
});

export const webhook_triggers = sqliteTable('webhook_triggers', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  name: text('name').notNull(),
  description: text('description'),
  webhookPath: text('webhook_path').notNull().unique(),
  provider: text('provider').notNull().default('generic'),
  isEnabled: integer('is_enabled', { mode: 'boolean' }).notNull().default(true),
  allowedMethods: text('allowed_methods').notNull().default('POST'),
  hmacEnabled: integer('hmac_enabled', { mode: 'boolean' }).notNull().default(false),
  hmacHeaderName: text('hmac_header_name'),
  hmacSecret: text('hmac_secret'),
  allowedIps: text('allowed_ips'),
  flowId: text('flow_id').references(() => flows.id, { onDelete: 'no action' }),
  nodeId: text('node_id'),
  lastTriggeredAt: text('last_triggered_at'),
  lastPayload: text('last_payload', { mode: 'json' }),
  triggerCount: integer('trigger_count').notNull().default(0),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const userRelations = relations(user, ({ many }) => ({
  account: many(account),
  session: many(session),
  rbac_team_members: many(rbac_team_members),
  rbac_teams: many(rbac_teams),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));

export const flowAccessRelations = relations(flowAccess, ({ one }) => ({
  flow: one(flows, { fields: [flowAccess.flowId], references: [flows.id] }),
}));

export const flowsRelations = relations(flows, ({ one, many }) => ({
  scope: one(rbac_teams, { fields: [flows.scope_id], references: [rbac_teams.id] }),
  flowAccess: many(flowAccess),
  flowTriggers: many(flowTriggers),
  flowVersions: many(flowVersions),
  chatMessages: many(chatMessages),
  flowRuns: many(flowRuns),
  webhook_triggers: many(webhook_triggers),
}));

export const flowTriggersRelations = relations(flowTriggers, ({ one }) => ({
  flow: one(flows, { fields: [flowTriggers.flowId], references: [flows.id] }),
}));

export const flowVersionsRelations = relations(flowVersions, ({ one }) => ({
  flow: one(flows, { fields: [flowVersions.flowId], references: [flows.id] }),
}));

export const chatMessagesRelations = relations(chatMessages, ({ one }) => ({
  flow: one(flows, { fields: [chatMessages.flowId], references: [flows.id] }),
}));

export const flowRunsRelations = relations(flowRuns, ({ one, many }) => ({
  flow: one(flows, { fields: [flowRuns.flowId], references: [flows.id] }),
  actionTraces: many(actionTraces),
  batchJobs: many(batchJobs),
}));

export const actionTracesRelations = relations(actionTraces, ({ one, many }) => ({
  flowRun: one(flowRuns, { fields: [actionTraces.flowRunId], references: [flowRuns.id] }),
  parentNodeExecution: one(actionTraces, {
    fields: [actionTraces.parentNodeExecutionId],
    references: [actionTraces.id],
  }),
  actionTraces: many(actionTraces),
}));

export const batchJobsRelations = relations(batchJobs, ({ one }) => ({
  flowRun: one(flowRuns, { fields: [batchJobs.flowRunId], references: [flowRuns.id] }),
}));

export const rbac_scope_accessRelations = relations(rbac_scope_access, ({ one }) => ({
  scope: one(rbac_teams, { fields: [rbac_scope_access.scope_id], references: [rbac_teams.id] }),
}));

export const rbac_team_membersRelations = relations(rbac_team_members, ({ one }) => ({
  team: one(rbac_teams, { fields: [rbac_team_members.team_id], references: [rbac_teams.id] }),
  user: one(user, { fields: [rbac_team_members.user_id], references: [user.id] }),
}));

export const rbac_teamsRelations = relations(rbac_teams, ({ one, many }) => ({
  parent: one(rbac_teams, { fields: [rbac_teams.parent_id], references: [rbac_teams.id] }),
  created_by: one(user, { fields: [rbac_teams.created_by], references: [user.id] }),
  flows: many(flows),
  rbac_scope_access: many(rbac_scope_access),
  rbac_team_members: many(rbac_team_members),
  rbac_teams: many(rbac_teams),
}));

export const webhook_triggersRelations = relations(webhook_triggers, ({ one }) => ({
  flow: one(flows, { fields: [webhook_triggers.flowId], references: [flows.id] }),
}));

export type User = typeof user.$inferSelect;
export type NewUser = typeof user.$inferInsert;
export type Account = typeof account.$inferSelect;
export type NewAccount = typeof account.$inferInsert;
export type Session = typeof session.$inferSelect;
export type NewSession = typeof session.$inferInsert;
export type Verification = typeof verification.$inferSelect;
export type NewVerification = typeof verification.$inferInsert;
export type FlowAccess = typeof flowAccess.$inferSelect;
export type NewFlowAccess = typeof flowAccess.$inferInsert;
export type Credentials = typeof credentials.$inferSelect;
export type NewCredentials = typeof credentials.$inferInsert;
export type Flows = typeof flows.$inferSelect;
export type NewFlows = typeof flows.$inferInsert;
export type FlowTriggers = typeof flowTriggers.$inferSelect;
export type NewFlowTriggers = typeof flowTriggers.$inferInsert;
export type FlowVersions = typeof flowVersions.$inferSelect;
export type NewFlowVersions = typeof flowVersions.$inferInsert;
export type ChatMessages = typeof chatMessages.$inferSelect;
export type NewChatMessages = typeof chatMessages.$inferInsert;
export type FlowRuns = typeof flowRuns.$inferSelect;
export type NewFlowRuns = typeof flowRuns.$inferInsert;
export type ActionTraces = typeof actionTraces.$inferSelect;
export type NewActionTraces = typeof actionTraces.$inferInsert;
export type BatchJobs = typeof batchJobs.$inferSelect;
export type NewBatchJobs = typeof batchJobs.$inferInsert;
export type Rbac_scope_access = typeof rbac_scope_access.$inferSelect;
export type NewRbac_scope_access = typeof rbac_scope_access.$inferInsert;
export type Rbac_team_members = typeof rbac_team_members.$inferSelect;
export type NewRbac_team_members = typeof rbac_team_members.$inferInsert;
export type Rbac_teams = typeof rbac_teams.$inferSelect;
export type NewRbac_teams = typeof rbac_teams.$inferInsert;
export type Webhook_triggers = typeof webhook_triggers.$inferSelect;
export type NewWebhook_triggers = typeof webhook_triggers.$inferInsert;
