/**
 * Drizzle Schema Generation Tests
 *
 * Tests the CLI's schema generators using realistic example schemas.
 * Mirrors the user-auth plugin's generate.test.ts approach:
 *   - Generate for each dialect (sqlite, postgresql, mysql)
 *   - Verify output contains expected table/column definitions
 *   - Verify dialect-specific code (pgEnum, mysqlEnum, sqliteTable, etc.)
 *   - Test with plugins that add tables, extend tables, and conflict
 */

import { describe, it, expect } from 'vitest';
import {
  mergeSchemas,
  generateSqliteSchema,
  generatePostgresSchema,
  generateMysqlSchema,
  CORE_TABLE_NAMES,
} from '@invect/core';

import {
  multiTenantPlugin,
  auditLogPlugin,
  ecommercePlugin,
  minimalPlugin,
  coreExtensionPlugin,
  analyticsPlugin,
  conflictingPlugin,
  disabledMigrationPlugin,
  pluginA,
  pluginB,
  conflictPluginA,
  conflictPluginB,
  authenticationPlugin,
} from './fixtures/example-schemas';

// =============================================================================
// Helper: generate all 3 dialect schemas from a plugin set
// =============================================================================

function generateAll(plugins: any[]) {
  const merged = mergeSchemas(plugins);
  return {
    merged,
    sqlite: generateSqliteSchema(merged),
    postgres: generatePostgresSchema(merged),
    mysql: generateMysqlSchema(merged),
  };
}

// =============================================================================
// 1. Core-only schema (no plugins)
// =============================================================================

describe('generate core-only schema (no plugins)', () => {
  const { sqlite, postgres, mysql, merged } = generateAll([]);

  it('should include all core tables', () => {
    for (const tableName of CORE_TABLE_NAMES) {
      const table = merged.tables.find((t) => t.name === tableName);
      expect(table, `missing table: ${tableName}`).toBeDefined();
      expect(table!.source).toBe('core');
    }
  });

  it('should generate valid SQLite schema', () => {
    expect(sqlite).toContain("from 'drizzle-orm/sqlite-core'");
    expect(sqlite).toContain(
      "import { BatchStatus, FlowRunStatus, NodeExecutionStatus } from '@invect/core';",
    );
    expect(sqlite).toContain("sqliteTable('flows'");
    expect(sqlite).toContain("sqliteTable('flow_versions'");
    expect(sqlite).toContain("sqliteTable('flow_executions'");
    expect(sqlite).toContain("sqliteTable('credentials'");
    expect(sqlite).toContain('default(FlowRunStatus.PENDING)');
    expect(sqlite).toContain('default(NodeExecutionStatus.PENDING)');
    // SQLite uses text for dates
    expect(sqlite).toContain("text('created_at')");
    // SQLite uses integer for booleans
    expect(sqlite).toContain("integer('is_active', { mode: 'boolean' })");
    // SQLite uses text({mode:'json'}) for JSON
    expect(sqlite).toContain("text('inputs', { mode: 'json' })");
  });

  it('should generate valid PostgreSQL schema', () => {
    expect(postgres).toContain("from 'drizzle-orm/pg-core'");
    expect(postgres).toContain("pgTable('flows'");
    expect(postgres).toContain("pgTable('flow_executions'");
    expect(postgres).toContain("pgTable('credentials'");
    // PG uses timestamp for dates
    expect(postgres).toContain("timestamp('created_at')");
    // PG uses boolean natively
    expect(postgres).toContain("boolean('is_active')");
    // PG uses json for JSON
    expect(postgres).toContain("json('inputs')");
    // PG has enum types
    expect(postgres).toContain('pgEnum(');
  });

  it('should generate valid MySQL schema', () => {
    expect(mysql).toContain("from 'drizzle-orm/mysql-core'");
    expect(mysql).toContain("mysqlTable('flows'");
    expect(mysql).toContain("mysqlTable('flow_executions'");
    expect(mysql).toContain("mysqlTable('credentials'");
    // MySQL uses timestamp for dates
    expect(mysql).toContain("timestamp('created_at')");
    // MySQL uses boolean
    expect(mysql).toContain("boolean('is_active')");
    // MySQL has enum types
    expect(mysql).toContain('mysqlEnum(');
  });

  it('should generate type exports for all tables', () => {
    for (const dialect of [sqlite, postgres, mysql]) {
      expect(dialect).toContain('export type Flows =');
      expect(dialect).toContain('export type NewFlows =');
      expect(dialect).toContain('export type Credentials =');
      expect(dialect).toContain('export type NewCredentials =');
    }
  });

  it('should include the AUTO-GENERATED header', () => {
    expect(sqlite).toContain('AUTO-GENERATED by @invect/cli');
    expect(postgres).toContain('AUTO-GENERATED by @invect/cli');
    expect(mysql).toContain('AUTO-GENERATED by @invect/cli');
  });

  it('should generate relations', () => {
    for (const dialect of [sqlite, postgres, mysql]) {
      expect(dialect).toContain('relations(');
    }
  });
});

// =============================================================================
// 1b. User Auth plugin — auth tables auto-discovered from plugin schema
// =============================================================================

describe('generate with user-auth plugin', () => {
  const { sqlite, postgres, mysql, merged } = generateAll([authenticationPlugin]);

  it('should include all 4 user-auth tables', () => {
    for (const tableName of ['user', 'session', 'account', 'verification']) {
      const table = merged.tables.find((t) => t.name === tableName);
      expect(table, `missing table: ${tableName}`).toBeDefined();
      expect(table!.source).toBe('user-auth');
    }
  });

  it('should generate user table with correct columns', () => {
    expect(sqlite).toContain("sqliteTable('user'");
    expect(sqlite).toContain("text('email')");
    expect(sqlite).toContain("text('name')");
    expect(postgres).toContain("pgTable('user'");
    expect(mysql).toContain("mysqlTable('user'");
  });

  it('should generate session table with foreign key to user', () => {
    expect(sqlite).toContain("sqliteTable('session'");
    expect(sqlite).toContain("text('user_id')");
    expect(postgres).toContain("pgTable('session'");
  });

  it('should generate account table', () => {
    expect(sqlite).toContain("sqliteTable('account'");
    expect(sqlite).toContain("text('provider_id')");
    expect(sqlite).toContain("text('account_id')");
  });

  it('should generate verification table', () => {
    expect(sqlite).toContain("sqliteTable('verification'");
    expect(sqlite).toContain("text('identifier')");
    expect(sqlite).toContain("text('value')");
  });

  it('should still include all core tables', () => {
    for (const tableName of CORE_TABLE_NAMES) {
      const table = merged.tables.find((t) => t.name === tableName);
      expect(table, `missing core table: ${tableName}`).toBeDefined();
    }
  });

  it('should have more tables than core-only', () => {
    const coreOnly = mergeSchemas([]);
    expect(merged.tables.length).toBe(coreOnly.tables.length + 4);
  });
});

// =============================================================================
// 2. Multi-Tenant SaaS plugin
// =============================================================================

describe('generate with multi-tenant plugin', () => {
  const { sqlite, postgres, mysql, merged } = generateAll([multiTenantPlugin]);

  it('should add tenants table', () => {
    const tenantsTable = merged.tables.find((t) => t.name === 'tenants');
    expect(tenantsTable).toBeDefined();
    expect(tenantsTable!.source).toBe('multi-tenant');
    expect(tenantsTable!.definition.fields.slug.unique).toBe(true);
  });

  it('should add tenantMembers table with composite PK', () => {
    const membersTable = merged.tables.find((t) => t.name === 'tenantMembers');
    expect(membersTable).toBeDefined();
    expect(membersTable!.definition.compositePrimaryKey).toEqual(['tenantId', 'userId']);
  });

  it('should extend flows table with tenantId', () => {
    const flowsTable = merged.tables.find((t) => t.name === 'flows');
    expect(flowsTable).toBeDefined();
    expect(flowsTable!.definition.fields.tenantId).toBeDefined();
    expect(flowsTable!.definition.fields.tenantId.references?.table).toBe('tenants');
  });

  it('SQLite: should include tenant tables and foreign keys', () => {
    expect(sqlite).toContain("sqliteTable('tenants'");
    expect(sqlite).toContain("sqliteTable('tenant_members'");
    expect(sqlite).toContain("text('slug')");
    expect(sqlite).toContain('.unique()');
    expect(sqlite).toContain('primaryKey(');
  });

  it('PostgreSQL: should generate enum for tenant plan', () => {
    expect(postgres).toContain("pgTable('tenants'");
    // Enum for plan column
    expect(postgres).toContain("'free'");
    expect(postgres).toContain("'enterprise'");
  });

  it('MySQL: should generate enum for tenant plan', () => {
    expect(mysql).toContain("mysqlTable('tenants'");
    expect(mysql).toContain("'free'");
    expect(mysql).toContain("'enterprise'");
  });

  it('should have more tables than core-only', () => {
    const coreOnly = mergeSchemas([]);
    expect(merged.tables.length).toBeGreaterThan(coreOnly.tables.length);
  });
});

// =============================================================================
// 3. E-Commerce plugin — multiple related tables with enums
// =============================================================================

describe('generate with e-commerce plugin', () => {
  const { sqlite, postgres, mysql, merged } = generateAll([ecommercePlugin]);

  it('should add products, customers, orders, orderItems tables', () => {
    expect(merged.tables.find((t) => t.name === 'products')).toBeDefined();
    expect(merged.tables.find((t) => t.name === 'customers')).toBeDefined();
    expect(merged.tables.find((t) => t.name === 'orders')).toBeDefined();
    expect(merged.tables.find((t) => t.name === 'orderItems')).toBeDefined();
  });

  it('should preserve foreign key relationships', () => {
    const ordersTable = merged.tables.find((t) => t.name === 'orders');
    expect(ordersTable!.definition.fields.customerId.references).toEqual({
      table: 'customers',
      field: 'id',
      onDelete: 'restrict',
    });

    const itemsTable = merged.tables.find((t) => t.name === 'orderItems');
    expect(itemsTable!.definition.fields.orderId.references).toEqual({
      table: 'orders',
      field: 'id',
      onDelete: 'cascade',
    });
  });

  it('SQLite: should generate order status as text (no enum)', () => {
    // SQLite doesn't have real enums, so they become text columns
    expect(sqlite).toContain("sqliteTable('orders'");
    expect(sqlite).toContain("text('status')");
  });

  it('PostgreSQL: should generate order status as pgEnum', () => {
    expect(postgres).toContain("pgTable('orders'");
    expect(postgres).toContain("'pending'");
    expect(postgres).toContain("'shipped'");
    expect(postgres).toContain("'refunded'");
  });

  it('MySQL: should generate order status as mysqlEnum', () => {
    expect(mysql).toContain("mysqlTable('orders'");
    expect(mysql).toContain("'pending'");
    expect(mysql).toContain("'delivered'");
  });

  it('should generate unique constraint on product SKU', () => {
    for (const dialect of [sqlite, postgres, mysql]) {
      expect(dialect).toContain('sku');
      expect(dialect).toContain('.unique()');
    }
  });

  it('should handle default values correctly', () => {
    // defaultValue: 0 for stockQuantity
    for (const dialect of [sqlite, postgres, mysql]) {
      expect(dialect).toContain('.default(0)');
    }
  });
});

// =============================================================================
// 4. Audit Log plugin — single new table, no FK to core
// =============================================================================

describe('generate with audit log plugin', () => {
  const { sqlite, postgres, mysql, merged } = generateAll([auditLogPlugin]);

  it('should add auditLogs table', () => {
    const table = merged.tables.find((t) => t.name === 'auditLogs');
    expect(table).toBeDefined();
    expect(table!.source).toBe('audit-log');
  });

  it('should generate for all dialects', () => {
    expect(sqlite).toContain("sqliteTable('audit_logs'");
    expect(postgres).toContain("pgTable('audit_logs'");
    expect(mysql).toContain("mysqlTable('audit_logs'");
  });

  it('should generate actor type enum', () => {
    // user, system, api_key, webhook
    expect(postgres).toContain("'api_key'");
    expect(mysql).toContain("'webhook'");
  });
});

// =============================================================================
// 5. Minimal plugin — simplest possible extension
// =============================================================================

describe('generate with minimal plugin', () => {
  const { sqlite, postgres, mysql, merged } = generateAll([minimalPlugin]);

  it('should add tags table', () => {
    const table = merged.tables.find((t) => t.name === 'tags');
    expect(table).toBeDefined();
    expect(table!.definition.fields.name.unique).toBe(true);
  });

  it('should generate for all dialects', () => {
    expect(sqlite).toContain("sqliteTable('tags'");
    expect(postgres).toContain("pgTable('tags'");
    expect(mysql).toContain("mysqlTable('tags'");
  });
});

// =============================================================================
// 6. Core-Extension-Only plugin — extends core tables, no new tables
// =============================================================================

describe('generate with core-extension-only plugin', () => {
  const { sqlite, postgres, mysql, merged } = generateAll([coreExtensionPlugin]);

  it('should not add new tables', () => {
    expect(merged.tables.length).toBe(CORE_TABLE_NAMES.length);
  });

  it('should extend flows table with ownerId, priority, category', () => {
    const flowsTable = merged.tables.find((t) => t.name === 'flows');
    expect(flowsTable!.definition.fields.ownerId).toBeDefined();
    expect(flowsTable!.definition.fields.priority).toBeDefined();
    expect(flowsTable!.definition.fields.category).toBeDefined();
  });

  it('should extend credentials table with rotatedAt, rotationPolicy', () => {
    const credTable = merged.tables.find((t) => t.name === 'credentials');
    expect(credTable!.definition.fields.rotatedAt).toBeDefined();
    expect(credTable!.definition.fields.rotationPolicy).toBeDefined();
  });

  it('should include new fields in generated output', () => {
    for (const dialect of [sqlite, postgres, mysql]) {
      expect(dialect).toContain('owner_id');
      expect(dialect).toContain('priority');
      expect(dialect).toContain('category');
      expect(dialect).toContain('rotated_at');
      expect(dialect).toContain('rotation_policy');
    }
  });
});

// =============================================================================
// 7. Analytics plugin — bigint columns
// =============================================================================

describe('generate with analytics plugin (bigint)', () => {
  const { sqlite, postgres, mysql } = generateAll([analyticsPlugin]);

  it('SQLite: should map bigint to integer', () => {
    expect(sqlite).toContain("sqliteTable('flow_analytics'");
    expect(sqlite).toContain("integer('total_runs')");
  });

  it('PostgreSQL: should use bigint', () => {
    expect(postgres).toContain("pgTable('flow_analytics'");
    expect(postgres).toContain("bigint('total_runs'");
  });

  it('MySQL: should use bigint', () => {
    expect(mysql).toContain("mysqlTable('flow_analytics'");
    expect(mysql).toContain("bigint('total_runs'");
  });
});

// =============================================================================
// 8. Multiple plugins combined — real-world scenario
// =============================================================================

describe('generate with multiple plugins', () => {
  const plugins = [multiTenantPlugin, auditLogPlugin, ecommercePlugin, minimalPlugin];
  const { merged, sqlite, postgres, mysql } = generateAll(plugins);

  it('should include all plugin tables', () => {
    const tableNames = merged.tables.map((t) => t.name);
    // Multi-tenant
    expect(tableNames).toContain('tenants');
    expect(tableNames).toContain('tenantMembers');
    // Audit log
    expect(tableNames).toContain('auditLogs');
    // E-commerce
    expect(tableNames).toContain('products');
    expect(tableNames).toContain('customers');
    expect(tableNames).toContain('orders');
    expect(tableNames).toContain('orderItems');
    // Minimal
    expect(tableNames).toContain('tags');
  });

  it('should have correct total count', () => {
    const expectedCount = CORE_TABLE_NAMES.length + 8; // 8 new plugin tables
    expect(merged.tables.length).toBe(expectedCount);
  });

  it('should still include all core tables', () => {
    const tableNames = merged.tables.map((t) => t.name);
    for (const coreName of CORE_TABLE_NAMES) {
      expect(tableNames).toContain(coreName);
    }
  });

  it('should generate all tables in each dialect', () => {
    for (const dialect of [sqlite, postgres, mysql]) {
      expect(dialect).toContain('tenants');
      expect(dialect).toContain('audit_logs');
      expect(dialect).toContain('products');
      expect(dialect).toContain('orders');
      expect(dialect).toContain('tags');
    }
  });

  it('should track provenance correctly', () => {
    const tenantProv = merged.provenance.find((p) => p.table === 'tenants' && p.field === null);
    expect(tenantProv?.source).toBe('multi-tenant');

    const auditProv = merged.provenance.find((p) => p.table === 'auditLogs' && p.field === null);
    expect(auditProv?.source).toBe('audit-log');

    const flowTenantIdProv = merged.provenance.find(
      (p) => p.table === 'flows' && p.field === 'tenantId',
    );
    expect(flowTenantIdProv?.source).toBe('multi-tenant');
  });
});

// =============================================================================
// 9. Two plugins extending same core table — non-conflicting
// =============================================================================

describe('two plugins extending same core table (non-conflicting)', () => {
  const { merged } = generateAll([pluginA, pluginB]);

  it('should merge both fields into flows table', () => {
    const flowsTable = merged.tables.find((t) => t.name === 'flows');
    expect(flowsTable!.definition.fields.pluginAField).toBeDefined();
    expect(flowsTable!.definition.fields.pluginBField).toBeDefined();
  });

  it('should track provenance per plugin', () => {
    const provA = merged.provenance.find((p) => p.table === 'flows' && p.field === 'pluginAField');
    expect(provA?.source).toBe('plugin-a');

    const provB = merged.provenance.find((p) => p.table === 'flows' && p.field === 'pluginBField');
    expect(provB?.source).toBe('plugin-b');
  });
});

// =============================================================================
// 10. Conflicting plugin — tries to override core field
// =============================================================================

describe('conflicting plugin — redefines core field', () => {
  it('should throw when a plugin redefines a core field', () => {
    expect(() => mergeSchemas([conflictingPlugin])).toThrow(/Schema merge errors/);
    expect(() => mergeSchemas([conflictingPlugin])).toThrow(
      /Field "name" on table "flows" already defined by "core"/,
    );
  });
});

// =============================================================================
// 11. Two plugins conflicting on the same NEW field
// =============================================================================

describe('two plugins conflicting on same new field', () => {
  it('should throw when two plugins define the same field on the same table', () => {
    expect(() => mergeSchemas([conflictPluginA, conflictPluginB])).toThrow(/Schema merge errors/);
    expect(() => mergeSchemas([conflictPluginA, conflictPluginB])).toThrow(/sharedField/);
  });
});

// =============================================================================
// 12. Disabled migration table
// =============================================================================

describe('disabled migration table', () => {
  const { merged } = generateAll([disabledMigrationPlugin]);

  it('should skip tables with disableMigration: true', () => {
    const tempTable = merged.tables.find((t) => t.name === 'tempData');
    expect(tempTable).toBeUndefined();
  });

  it('should include tables without disableMigration', () => {
    const enabledTable = merged.tables.find((t) => t.name === 'enabledTable');
    expect(enabledTable).toBeDefined();
  });
});

// =============================================================================
// 13. Dialect-specific column mapping
// =============================================================================

describe('dialect-specific column type mapping', () => {
  // Use e-commerce schema which exercises most field types
  const { sqlite, postgres, mysql } = generateAll([ecommercePlugin, analyticsPlugin]);

  describe('SQLite column types', () => {
    it('maps string → text', () => {
      expect(sqlite).toContain("text('name')");
    });
    it('maps uuid → text', () => {
      expect(sqlite).toContain("text('id')");
    });
    it('maps number → integer', () => {
      expect(sqlite).toContain("integer('quantity')");
    });
    it('maps boolean → integer with boolean mode', () => {
      expect(sqlite).toContain("integer('is_published', { mode: 'boolean' })");
    });
    it('maps date → text', () => {
      expect(sqlite).toContain("text('created_at')");
    });
    it('maps json → text with json mode', () => {
      expect(sqlite).toContain("{ mode: 'json' }");
    });
    it('maps bigint → integer', () => {
      expect(sqlite).toContain("integer('total_runs')");
    });
  });

  describe('PostgreSQL column types', () => {
    it('maps string → text', () => {
      expect(postgres).toContain("text('name')");
    });
    it('maps uuid → uuid', () => {
      expect(postgres).toContain("uuid('id')");
    });
    it('maps number → integer', () => {
      expect(postgres).toContain("integer('quantity')");
    });
    it('maps boolean → boolean', () => {
      expect(postgres).toContain("boolean('is_published')");
    });
    it('maps date → timestamp', () => {
      expect(postgres).toContain("timestamp('created_at')");
    });
    it('maps json → json', () => {
      expect(postgres).toContain("json('metadata')");
    });
    it('maps bigint → bigint', () => {
      expect(postgres).toContain("bigint('total_runs'");
    });
  });

  describe('MySQL column types', () => {
    it('maps string → varchar', () => {
      expect(mysql).toContain("varchar('name'");
    });
    it('maps uuid → varchar(36)', () => {
      expect(mysql).toContain("varchar('id'");
    });
    it('maps number → int', () => {
      expect(mysql).toContain("int('quantity')");
    });
    it('maps boolean → boolean', () => {
      expect(mysql).toContain("boolean('is_published')");
    });
    it('maps date → timestamp', () => {
      expect(mysql).toContain("timestamp('created_at')");
    });
    it('maps json → json', () => {
      expect(mysql).toContain("json('metadata')");
    });
    it('maps bigint → bigint', () => {
      expect(mysql).toContain("bigint('total_runs'");
    });
  });
});

// =============================================================================
// 14. Default value generation
// =============================================================================

describe('default value generation', () => {
  const { sqlite, postgres, mysql } = generateAll([ecommercePlugin]);

  it('SQLite: uuid() default uses $defaultFn', () => {
    expect(sqlite).toContain('$defaultFn(() => randomUUID())');
  });

  it('SQLite: now() default uses CURRENT_TIMESTAMP', () => {
    expect(sqlite).toContain('CURRENT_TIMESTAMP');
  });

  it('PostgreSQL: now() default uses defaultNow()', () => {
    expect(postgres).toContain('.defaultNow()');
  });

  it('should generate string defaults with quotes', () => {
    // e.g., defaultValue: 'USD' for currency
    for (const dialect of [sqlite, postgres, mysql]) {
      expect(dialect).toContain(".default('USD')");
    }
  });

  it('should generate numeric defaults without quotes', () => {
    for (const dialect of [sqlite, postgres, mysql]) {
      expect(dialect).toContain('.default(0)');
    }
  });

  it('should generate boolean defaults', () => {
    for (const dialect of [sqlite, postgres, mysql]) {
      expect(dialect).toContain('.default(false)');
    }
  });
});

// =============================================================================
// 15. Foreign key generation
// =============================================================================

describe('foreign key generation', () => {
  const { sqlite, postgres, mysql } = generateAll([ecommercePlugin]);

  it('SQLite: generates .references()', () => {
    expect(sqlite).toContain('.references(');
    expect(sqlite).toContain("onDelete: 'cascade'");
    expect(sqlite).toContain("onDelete: 'restrict'");
  });

  it('PostgreSQL: generates .references()', () => {
    expect(postgres).toContain('.references(');
    expect(postgres).toContain("onDelete: 'cascade'");
    expect(postgres).toContain("onDelete: 'restrict'");
  });

  it('MySQL: generates .references()', () => {
    expect(mysql).toContain('.references(');
    expect(mysql).toContain("onDelete: 'cascade'");
    expect(mysql).toContain("onDelete: 'restrict'");
  });
});

// =============================================================================
// 16. Composite primary key generation
// =============================================================================

describe('composite primary key generation', () => {
  const { sqlite, postgres, mysql } = generateAll([multiTenantPlugin]);

  it('should generate composite PK for tenantMembers', () => {
    // All dialects use primaryKey({ columns: [...] })
    for (const dialect of [sqlite, postgres, mysql]) {
      expect(dialect).toContain('primaryKey(');
      expect(dialect).toContain('table.tenantId');
      expect(dialect).toContain('table.userId');
    }
  });
});

// =============================================================================
// 17. TypeAnnotation ($type<>()) generation
// =============================================================================

describe('$type<>() annotation generation', () => {
  const { sqlite, postgres, mysql } = generateAll([]);

  it('should generate $type<> for typed JSON columns', () => {
    for (const dialect of [sqlite, postgres, mysql]) {
      // e.g., credentials.config has typeAnnotation: 'CredentialConfig'
      expect(dialect).toContain('$type<CredentialConfig>()');
    }
    // Enum columns: SQLite uses text() so needs $type<>() for type safety,
    // but Postgres/MySQL use pgEnum/mysqlEnum which already type correctly.
    expect(sqlite).toContain('$type<FlowRunStatus>()');
    expect(postgres).not.toContain('$type<FlowRunStatus>()');
    expect(mysql).not.toContain('$type<FlowRunStatus>()');
  });
});

// =============================================================================
// 18. Schema determinism (idempotent generation)
// =============================================================================

describe('schema generation is deterministic', () => {
  it('should produce identical output on repeated calls', () => {
    const plugins = [multiTenantPlugin, ecommercePlugin, auditLogPlugin];

    const first = generateAll(plugins);
    const second = generateAll(plugins);

    expect(first.sqlite).toBe(second.sqlite);
    expect(first.postgres).toBe(second.postgres);
    expect(first.mysql).toBe(second.mysql);
  });
});

// =============================================================================
// 19. FK reference resolution (tableName → JS variable name)
// =============================================================================

describe('foreign key references use correct JS variable names', () => {
  const { sqlite, postgres, mysql } = generateAll([]);

  it('should generate action_traces table in all dialects', () => {
    // Verify core tables are present in all dialects
    expect(sqlite).toContain("sqliteTable('action_traces'");
    expect(postgres).toContain("pgTable('action_traces'");
    expect(mysql).toContain("mysqlTable('action_traces'");
  });

  it('should reference flowRuns (not flowExecutions) in FK columns', () => {
    // flowRuns has tableName: 'flow_executions', so the DB name is flow_executions
    // but the JS variable is flowRuns. Naive camelCase would give flowExecutions.
    for (const dialect of [sqlite, postgres, mysql]) {
      expect(dialect).toContain('.references(() => flowRuns.id');
      // A naive camelCase of 'flow_executions' would be 'flowExecutions' — should NOT appear
      expect(dialect).not.toContain('.references(() => flowExecutions.');
    }
  });

  it('should reference all FK targets using their JS variable names', () => {
    // Ensure no snake_case table names leak into .references() calls
    for (const dialect of [sqlite, postgres, mysql]) {
      const refMatches = dialect.match(/\.references\(\(\) => (\w+)\./g) || [];
      for (const ref of refMatches) {
        // Extract the variable name from .references(() => varName.field
        const varName = ref.match(/=> (\w+)\./)?.[1];
        expect(varName, `FK reference contains underscore: ${ref}`).not.toContain('_');
      }
    }
  });
});

// =============================================================================
// 20. Append-mode schema generation
// =============================================================================

describe('append-mode schema generators', () => {
  const {
    generateSqliteSchemaAppend,
    generatePostgresSchemaAppend,
    generateMysqlSchemaAppend,
  } = require('@invect/core');

  const merged = mergeSchemas([]);

  it('should generate SQLite append-mode schema with imports and code', () => {
    const result = generateSqliteSchemaAppend(merged);
    expect(result.imports[0]).toContain('drizzle-orm/sqlite-core');
    expect(result.imports).toContainEqual(
      expect.stringContaining('BatchStatus, FlowRunStatus, NodeExecutionStatus'),
    );
    expect(result.imports).toContainEqual(expect.stringContaining("from '@invect/core/types'"));
    expect(result.code).toContain('Invect tables — AUTO-GENERATED');
    expect(result.code).toContain('sqliteTable');
    expect(result.code).toContain('relations(');
    expect(result.code).toContain('default(FlowRunStatus.PENDING)');
    expect(result.code).toContain('default(NodeExecutionStatus.PENDING)');
    // Should NOT contain import statements in the code portion
    expect(result.code).not.toContain("from 'drizzle-orm");
  });

  it('should generate PostgreSQL append-mode schema', () => {
    const result = generatePostgresSchemaAppend(merged);
    expect(result.imports.length).toBeGreaterThanOrEqual(4);
    expect(result.imports[0]).toContain('drizzle-orm/pg-core');
    expect(result.code).toContain('pgTable');
    expect(result.code).toContain('pgEnum');
  });

  it('should generate MySQL append-mode schema', () => {
    const result = generateMysqlSchemaAppend(merged);
    expect(result.imports.length).toBeGreaterThanOrEqual(4);
    expect(result.imports[0]).toContain('drizzle-orm/mysql-core');
    expect(result.code).toContain('mysqlTable');
  });

  it('append-mode should also fix FK references', () => {
    const result = generateSqliteSchemaAppend(merged);
    // FK references should use correct JS variable names
    expect(result.code).toContain('.references(() => flowRuns.id');
  });

  it('append-mode should include type exports', () => {
    const result = generateSqliteSchemaAppend(merged);
    expect(result.code).toContain('export type Flows =');
    expect(result.code).toContain('export type NewFlows =');
    expect(result.code).toContain('export type Credentials =');
  });
});
