import type { PrimitiveFlowDefinition } from '@invect/primitives';
import { analyzeFlow } from './control-flow';
import { emitOrchestratorBody, emitStepFunctions, sanitizeIdent } from './step-emitter';

export interface CompileOptions {
  // Name of the exported workflow function, e.g. "myFlowWorkflow".
  workflowName: string;

  // Import path + named export for the flow definition. The generated file
  // imports this so param functions can be called inside step bodies.
  //   import { <flowExport> } from '<flowImport>'
  flowImport: string;
  flowExport: string;

  // Import path + named export returning FlowRunnerConfig. The generated step
  // functions call this inside each "use step" body — fresh per invocation.
  //   import { <configExport> } from '<configImport>'
  configImport: string;
  configExport: string;

  // Optional header prepended to the file (e.g. a provenance comment).
  header?: string;
}

export interface CompileResult {
  code: string;
  stepCount: number;
  outputCount: number;
  warnings: string[];
}

// Validate that sanitized referenceIds remain unique so step_<ident> functions
// don't collide. Returns a list of any collisions as human-readable strings.
function findIdentCollisions(refs: string[]): string[] {
  const byIdent = new Map<string, string[]>();
  for (const r of refs) {
    const ident = sanitizeIdent(r);
    if (!byIdent.has(ident)) byIdent.set(ident, []);
    byIdent.get(ident)!.push(r);
  }
  const collisions: string[] = [];
  for (const [ident, originals] of byIdent) {
    if (originals.length > 1) {
      collisions.push(`"${originals.join('", "')}" all sanitize to "${ident}"`);
    }
  }
  return collisions;
}

export function compile(
  flow: PrimitiveFlowDefinition,
  options: CompileOptions,
): CompileResult {
  const warnings: string[] = [];

  const collisions = findIdentCollisions(flow.nodes.map((n) => n.referenceId));
  if (collisions.length > 0) {
    throw new Error(
      `Flow contains referenceIds that collide after identifier sanitization: ${collisions.join('; ')}`,
    );
  }

  const { blocks, outputNodes, topoOrder } = analyzeFlow(flow);
  const outputNodeSet = new Set(outputNodes);

  if (outputNodes.length === 0) {
    warnings.push(
      'Flow has no output nodes; compiled workflow will always return an empty object',
    );
  }

  // Non-plain-object output warning: if a node's mapper or params look like they
  // produce class instances, devalue may fail at step boundaries. Best-effort.
  // (Skipped for now — the runtime will surface clear errors.)

  const orchestratorBody = emitOrchestratorBody(blocks, {
    flow,
    outputNodeSet,
  });

  const stepFns = emitStepFunctions(topoOrder);

  const header = options.header
    ? options.header
        .split('\n')
        .map((l) => (l.startsWith('//') ? l : `// ${l}`))
        .join('\n') + '\n'
    : '';

  const code = [
    '/* eslint-disable */',
    '// @generated by @invect/vercel-workflows — DO NOT EDIT.',
    header ? header.trimEnd() : '',
    `import { fetch } from 'workflow';`,
    `import { executeStep } from '@invect/vercel-workflows/runtime';`,
    `import type { ActionResult } from '@invect/vercel-workflows/runtime';`,
    `import { ${options.flowExport} as __flow } from ${JSON.stringify(options.flowImport)};`,
    `import { ${options.configExport} as __getConfig } from ${JSON.stringify(options.configImport)};`,
    '',
    'function __extractPrimary(r: ActionResult): unknown {',
    '  if (r.outputVariables) {',
    '    const vars = Object.values(r.outputVariables);',
    '    if (vars.length > 0) return vars[0]?.value;',
    '  }',
    '  return r.output;',
    '}',
    '',
    `export async function ${options.workflowName}(`,
    '  __inputs: Record<string, unknown> = {},',
    '): Promise<Record<string, unknown>> {',
    `  'use workflow';`,
    '  globalThis.fetch = fetch;',
    '',
    '  const __flowRunId = crypto.randomUUID();',
    '  const completedOutputs: Record<string, unknown> = {};',
    '  const flowOutputs: Record<string, unknown> = {};',
    '',
    orchestratorBody,
    '',
    '  return flowOutputs;',
    '}',
    '',
    '// ── step functions (one per node) ──────────────────────────────────────',
    '',
    stepFns,
    '',
  ]
    .filter((line) => line !== null && line !== undefined)
    .join('\n');

  return {
    code,
    stepCount: topoOrder.length,
    outputCount: outputNodes.length,
    warnings,
  };
}
