import {
  sqliteTable,
  text,
  integer,
  primaryKey,
  type AnySQLiteColumn,
} from 'drizzle-orm/sqlite-core';
import { relations, sql } from 'drizzle-orm';
import { randomUUID } from 'crypto';
import { BatchStatus, FlowRunStatus, NodeExecutionStatus } from '@invect/core';
import type {
  BatchProvider,
  CredentialAuthType,
  CredentialConfig,
  CredentialType,
  InvectDefinitionRuntime,
  JSONValue,
  TriggerType,
} from '@invect/core/types';

// =============================================================================
// Invect tables — AUTO-GENERATED by @invect/cli
// Do not edit below this line. Run `npx invect-cli generate` to regenerate.
// =============================================================================

export const credentials = sqliteTable('invect_credentials', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  name: text('name').notNull(),
  type: text('type').$type<CredentialType>().notNull(),
  authType: text('auth_type').$type<CredentialAuthType>().notNull(),
  config: text('config', { mode: 'json' }).$type<CredentialConfig>().notNull(),
  description: text('description'),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  workspaceId: text('workspace_id'),
  isShared: integer('is_shared', { mode: 'boolean' }).notNull().default(false),
  metadata: text('metadata', { mode: 'json' }).$type<Record<string, unknown>>(),
  lastUsedAt: text('last_used_at'),
  expiresAt: text('expires_at'),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const flows = sqliteTable('invect_flows', {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  description: text('description'),
  tags: text('tags', { mode: 'json' }).$type<string[]>(),
  isActive: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  liveVersionNumber: integer('live_version_number'),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const flowTriggers = sqliteTable('invect_flow_triggers', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  flowId: text('flow_id')
    .notNull()
    .references(() => flows.id, { onDelete: 'cascade' }),
  nodeId: text('node_id').notNull(),
  type: text('type').$type<TriggerType>().notNull(),
  isEnabled: integer('is_enabled', { mode: 'boolean' }).notNull().default(true),
  webhookPath: text('webhook_path').unique(),
  webhookSecret: text('webhook_secret'),
  cronExpression: text('cron_expression'),
  cronTimezone: text('cron_timezone'),
  lastTriggeredAt: text('last_triggered_at'),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const flowVersions = sqliteTable(
  'invect_flow_versions',
  {
    flowId: text('flow_id')
      .notNull()
      .references(() => flows.id, { onDelete: 'cascade' }),
    version: integer('version').notNull(),
    invectDefinition: text('invect_definition', { mode: 'json' })
      .$type<InvectDefinitionRuntime>()
      .notNull(),
    createdAt: text('created_at')
      .notNull()
      .default(sql`CURRENT_TIMESTAMP`),
    createdBy: text('created_by'),
  },
  (table) => [primaryKey({ columns: [table.version, table.flowId] })],
);

export const chatMessages = sqliteTable('invect_chat_messages', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  flowId: text('flow_id')
    .notNull()
    .references(() => flows.id, { onDelete: 'cascade' }),
  role: text('role').$type<'invect_user' | 'assistant' | 'system' | 'tool'>().notNull(),
  content: text('content').notNull().default(''),
  toolMeta: text('tool_meta', { mode: 'json' }).$type<Record<string, unknown>>(),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const flowRuns = sqliteTable('invect_flow_executions', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  flowId: text('flow_id')
    .notNull()
    .references(() => flows.id, { onDelete: 'cascade' }),
  flowVersion: integer('flow_version').notNull(),
  status: text('status').$type<FlowRunStatus>().notNull().default(FlowRunStatus.PENDING),
  inputs: text('inputs', { mode: 'json' }).$type<JSONValue>().notNull(),
  outputs: text('outputs', { mode: 'json' }).$type<JSONValue>(),
  error: text('error'),
  startedAt: text('started_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  completedAt: text('completed_at'),
  duration: integer('duration'),
  createdBy: text('created_by'),
  triggerType: text('trigger_type'),
  triggerId: text('trigger_id'),
  triggerNodeId: text('trigger_node_id'),
  triggerData: text('trigger_data', { mode: 'json' }).$type<JSONValue>(),
  lastHeartbeatAt: text('last_heartbeat_at'),
  nodeOutputs: text('node_outputs', { mode: 'json' }).$type<JSONValue>(),
});

export const actionTraces = sqliteTable('invect_action_traces', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  flowRunId: text('flow_run_id')
    .notNull()
    .references(() => flowRuns.id, { onDelete: 'cascade' }),
  parentNodeExecutionId: text('parent_node_execution_id').references(
    (): AnySQLiteColumn => actionTraces.id,
    { onDelete: 'cascade' },
  ),
  nodeId: text('node_id'),
  nodeType: text('node_type'),
  toolId: text('tool_id'),
  toolName: text('tool_name'),
  iteration: integer('iteration'),
  status: text('status')
    .$type<NodeExecutionStatus>()
    .notNull()
    .default(NodeExecutionStatus.PENDING),
  inputs: text('inputs', { mode: 'json' }).$type<JSONValue>().notNull(),
  outputs: text('outputs', { mode: 'json' }).$type<JSONValue>(),
  error: text('error'),
  startedAt: text('started_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  completedAt: text('completed_at'),
  duration: integer('duration'),
  retryCount: integer('retry_count').notNull().default(0),
});

export const batchJobs = sqliteTable('invect_batch_jobs', {
  id: text('id')
    .primaryKey()
    .notNull()
    .$defaultFn(() => randomUUID()),
  flowRunId: text('flow_run_id')
    .notNull()
    .references(() => flowRuns.id, { onDelete: 'cascade' }),
  nodeId: text('node_id').notNull(),
  provider: text('provider').$type<BatchProvider>().notNull(),
  batchId: text('batch_id'),
  status: text('status').$type<BatchStatus>().notNull().default(BatchStatus.SUBMITTED),
  requestData: text('request_data', { mode: 'json' }).notNull(),
  responseData: text('response_data', { mode: 'json' }),
  error: text('error'),
  submittedAt: text('submitted_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  completedAt: text('completed_at'),
  createdAt: text('created_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at')
    .notNull()
    .default(sql`CURRENT_TIMESTAMP`),
});

export const flowsRelations = relations(flows, ({ many }) => ({
  flowTriggers: many(flowTriggers),
  flowVersions: many(flowVersions),
  chatMessages: many(chatMessages),
  flowRuns: many(flowRuns),
}));

export const flowTriggersRelations = relations(flowTriggers, ({ one }) => ({
  flow: one(flows, { fields: [flowTriggers.flowId], references: [flows.id] }),
}));

export const flowVersionsRelations = relations(flowVersions, ({ one }) => ({
  flow: one(flows, { fields: [flowVersions.flowId], references: [flows.id] }),
}));

export const chatMessagesRelations = relations(chatMessages, ({ one }) => ({
  flow: one(flows, { fields: [chatMessages.flowId], references: [flows.id] }),
}));

export const flowRunsRelations = relations(flowRuns, ({ one, many }) => ({
  flow: one(flows, { fields: [flowRuns.flowId], references: [flows.id] }),
  actionTraces: many(actionTraces),
  batchJobs: many(batchJobs),
}));

export const actionTracesRelations = relations(actionTraces, ({ one, many }) => ({
  flowRun: one(flowRuns, { fields: [actionTraces.flowRunId], references: [flowRuns.id] }),
  parentNodeExecution: one(actionTraces, {
    fields: [actionTraces.parentNodeExecutionId],
    references: [actionTraces.id],
  }),
  actionTraces: many(actionTraces),
}));

export const batchJobsRelations = relations(batchJobs, ({ one }) => ({
  flowRun: one(flowRuns, { fields: [batchJobs.flowRunId], references: [flowRuns.id] }),
}));

export type Credentials = typeof credentials.$inferSelect;
export type NewCredentials = typeof credentials.$inferInsert;
export type Flows = typeof flows.$inferSelect;
export type NewFlows = typeof flows.$inferInsert;
export type FlowTriggers = typeof flowTriggers.$inferSelect;
export type NewFlowTriggers = typeof flowTriggers.$inferInsert;
export type FlowVersions = typeof flowVersions.$inferSelect;
export type NewFlowVersions = typeof flowVersions.$inferInsert;
export type ChatMessages = typeof chatMessages.$inferSelect;
export type NewChatMessages = typeof chatMessages.$inferInsert;
export type FlowRuns = typeof flowRuns.$inferSelect;
export type NewFlowRuns = typeof flowRuns.$inferInsert;
export type ActionTraces = typeof actionTraces.$inferSelect;
export type NewActionTraces = typeof actionTraces.$inferInsert;
export type BatchJobs = typeof batchJobs.$inferSelect;
export type NewBatchJobs = typeof batchJobs.$inferInsert;
