version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nest-prisma-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: invect
      POSTGRES_PASSWORD: invect
      POSTGRES_DB: acme_saas
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U invect -d acme_saas']
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata:
