/**
 * Acme Dashboard — Pre-existing App Schema
 *
 * This represents the schema a startup would already have BEFORE
 * adding Invect. It's a simple SaaS admin backend with customers,
 * products, orders, and team members.
 *
 * When Invect is added, `npx invect generate` merges Invect's
 * core tables + plugin tables INTO the same schema file, so
 * Drizzle Kit manages everything together.
 */

import { pgTable, text, integer, boolean, doublePrecision, timestamp, json, primaryKey } from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { randomUUID } from 'crypto';

// ─── Invect type aliases (used by $type<>() for type-safe queries) ──
type JSONValue = string | number | boolean | null | JSONValue[] | { [key: string]: JSONValue };
type CredentialType = 'api_key' | 'oauth2' | 'bearer_token' | 'basic_auth' | 'custom' | 'webhook';
type CredentialAuthType = 'api_key' | 'oauth2' | 'bearer_token' | 'basic_auth' | 'custom' | 'webhook';
type CredentialConfig = Record<string, unknown>;
type FlowAccessPermission = 'viewer' | 'operator' | 'editor' | 'owner';
type TriggerType = 'manual' | 'cron' | 'webhook';
type InvectDefinitionRuntime = Record<string, unknown>;
type FlowRunStatus = 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED' | 'PAUSED_FOR_BATCH';
type NodeExecutionStatus = 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'SKIPPED';
type BatchProvider = 'openai' | 'anthropic';
type BatchStatus = 'SUBMITTED' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED' | 'CANCELLED' | 'EXPIRED';

// ─────────────────────────────────────────────────────────────
// Team Members (used by better-auth as the "user" table)
// ─────────────────────────────────────────────────────────────

export const teamMembers = pgTable('team_members', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  role: text('role').notNull().default('member'),
  department: text('department'),
  avatarUrl: text('avatar_url'),
  isActive: boolean('is_active').notNull().default(true),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

// ─────────────────────────────────────────────────────────────
// Customers
// ─────────────────────────────────────────────────────────────

export const customers = pgTable('customers', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  company: text('company'),
  phone: text('phone'),
  plan: text('plan').notNull().default('free'),
  mrr: doublePrecision('mrr').notNull().default(0),
  status: text('status').notNull().default('trial'),
  notes: text('notes'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

// ─────────────────────────────────────────────────────────────
// Products
// ─────────────────────────────────────────────────────────────

export const products = pgTable('products', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  description: text('description'),
  sku: text('sku').notNull().unique(),
  priceInCents: integer('price_in_cents').notNull(),
  category: text('category').notNull().default('saas'),
  isActive: boolean('is_active').notNull().default(true),
  stockCount: integer('stock_count').notNull().default(0),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

// ─────────────────────────────────────────────────────────────
// Orders
// ─────────────────────────────────────────────────────────────

export const orders = pgTable('orders', {
  id: text('id').primaryKey(),
  customerId: text('customer_id')
    .notNull()
    .references(() => customers.id, { onDelete: 'cascade' }),
  status: text('status').notNull().default('pending'),
  totalInCents: integer('total_in_cents').notNull().default(0),
  currency: text('currency').notNull().default('usd'),
  notes: text('notes'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const orderItems = pgTable('order_items', {
  id: text('id').primaryKey(),
  orderId: text('order_id')
    .notNull()
    .references(() => orders.id, { onDelete: 'cascade' }),
  productId: text('product_id')
    .notNull()
    .references(() => products.id),
  quantity: integer('quantity').notNull().default(1),
  unitPriceInCents: integer('unit_price_in_cents').notNull(),
});

// =============================================================================
// Invect tables — AUTO-GENERATED by @invect/cli
// Do not edit below this line. Run `npx invect generate` to regenerate.
// =============================================================================

export const user = pgTable('user', {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').notNull().default(false),
  image: text('image'),
  role: text('role').default('editor'),
  banned: boolean('banned').default(false),
  banReason: text('ban_reason'),
  banExpires: timestamp('ban_expires'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const account = pgTable('account', {
  id: text('id').primaryKey().notNull(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: timestamp('access_token_expires_at'),
  refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
  scope: text('scope'),
  password: text('password'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const session = pgTable('session', {
  id: text('id').primaryKey().notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  token: text('token').notNull().unique(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  impersonatedBy: text('impersonated_by'),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
});

export const verification = pgTable('verification', {
  id: text('id').primaryKey().notNull(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: timestamp('expires_at').notNull(),
  createdAt: timestamp('created_at'),
  updatedAt: timestamp('updated_at'),
});

export const credentials = pgTable('credentials', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  name: text('name').notNull(),
  type: text('type').$type<CredentialType>().notNull(),
  authType: text('auth_type').$type<CredentialAuthType>().notNull(),
  config: json('config').$type<CredentialConfig>().notNull(),
  description: text('description'),
  isActive: boolean('is_active').notNull().default(true),
  workspaceId: text('workspace_id'),
  isShared: boolean('is_shared').notNull().default(false),
  metadata: json('metadata').$type<Record<string, unknown>>(),
  lastUsedAt: timestamp('last_used_at'),
  expiresAt: timestamp('expires_at'),
  webhookPath: text('webhook_path').unique(),
  webhookSecret: text('webhook_secret'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const flows = pgTable('flows', {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  description: text('description'),
  tags: json('tags').$type<string[]>(),
  scopeId: text('scope_id'),
  isActive: boolean('is_active').notNull().default(true),
  liveVersionNumber: integer('live_version_number'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const rbacTeams = pgTable('rbac_teams', {
  id: text('id').primaryKey().notNull(),
  name: text('name').notNull(),
  description: text('description'),
  parentId: text('parent_id'),
  createdBy: text('created_by').references(() => user.id),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at'),
});

export const rbacTeamMembers = pgTable('rbac_team_members', {
  id: text('id').primaryKey().notNull(),
  teamId: text('team_id').notNull().references(() => rbacTeams.id, { onDelete: 'cascade' }),
  userId: text('user_id').notNull().references(() => user.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const rbacScopeAccess = pgTable('rbac_scope_access', {
  id: text('id').primaryKey().notNull(),
  scopeId: text('scope_id').notNull().references(() => rbacTeams.id, { onDelete: 'cascade' }),
  userId: text('user_id'),
  teamId: text('team_id'),
  permission: text('permission').$type<FlowAccessPermission>().notNull().default('viewer'),
  grantedBy: text('granted_by'),
  grantedAt: timestamp('granted_at').notNull().defaultNow(),
});

export const flowAccess = pgTable('flow_access', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  userId: text('user_id'),
  teamId: text('team_id'),
  permission: text('permission').$type<FlowAccessPermission>().notNull().default('viewer'),
  grantedBy: text('granted_by'),
  grantedAt: timestamp('granted_at').notNull().defaultNow(),
  expiresAt: timestamp('expires_at'),
});

export const flowTriggers = pgTable('flow_triggers', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  nodeId: text('node_id').notNull(),
  type: text('type').$type<TriggerType>().notNull(),
  isEnabled: boolean('is_enabled').notNull().default(true),
  webhookPath: text('webhook_path').unique(),
  webhookSecret: text('webhook_secret'),
  cronExpression: text('cron_expression'),
  cronTimezone: text('cron_timezone'),
  lastTriggeredAt: timestamp('last_triggered_at'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const flowVersions = pgTable('flow_versions', {
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  version: integer('version').notNull(),
  invectDefinition: json('invect_definition').$type<InvectDefinitionRuntime>().notNull(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  createdBy: text('created_by'),
}, (table) => [primaryKey({ columns: [table.version, table.flowId] })]);

export const chatMessages = pgTable('chat_messages', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  role: text('role').$type<'user' | 'assistant' | 'system' | 'tool'>().notNull(),
  content: text('content').notNull().default(''),
  toolMeta: json('tool_meta').$type<Record<string, unknown>>(),
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export const flowRuns = pgTable('flow_executions', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowId: text('flow_id').notNull().references(() => flows.id, { onDelete: 'cascade' }),
  flowVersion: integer('flow_version').notNull(),
  status: text('status').$type<FlowRunStatus>().notNull().default('PENDING'),
  inputs: json('inputs').$type<JSONValue>().notNull(),
  outputs: json('outputs').$type<JSONValue>(),
  error: text('error'),
  startedAt: timestamp('started_at').notNull().defaultNow(),
  completedAt: timestamp('completed_at'),
  duration: integer('duration'),
  createdBy: text('created_by'),
  triggerType: text('trigger_type'),
  triggerId: text('trigger_id'),
  triggerNodeId: text('trigger_node_id'),
  triggerData: json('trigger_data').$type<JSONValue>(),
  lastHeartbeatAt: timestamp('last_heartbeat_at'),
});

export const nodeExecutions = pgTable('execution_traces', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowRunId: text('flow_run_id').notNull().references(() => flowRuns.id, { onDelete: 'cascade' }),
  nodeId: text('node_id').notNull(),
  nodeType: text('node_type').notNull(),
  status: text('status').$type<NodeExecutionStatus>().notNull().default('PENDING'),
  inputs: json('inputs').$type<JSONValue>().notNull(),
  outputs: json('outputs').$type<JSONValue>(),
  error: text('error'),
  startedAt: timestamp('started_at').notNull().defaultNow(),
  completedAt: timestamp('completed_at'),
  duration: integer('duration'),
  retryCount: integer('retry_count').notNull().default(0),
});

export const batchJobs = pgTable('batch_jobs', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  flowRunId: text('flow_run_id').notNull().references(() => flowRuns.id, { onDelete: 'cascade' }),
  nodeId: text('node_id').notNull(),
  provider: text('provider').$type<BatchProvider>().notNull(),
  batchId: text('batch_id'),
  status: text('status').$type<BatchStatus>().notNull().default('SUBMITTED'),
  requestData: json('request_data').notNull(),
  responseData: json('response_data'),
  error: text('error'),
  submittedAt: timestamp('submitted_at').notNull().defaultNow(),
  completedAt: timestamp('completed_at'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const agentToolExecutions = pgTable('agent_tool_executions', {
  id: text('id').primaryKey().notNull().$defaultFn(() => randomUUID()),
  nodeExecutionId: text('node_execution_id').notNull().references(() => nodeExecutions.id, { onDelete: 'cascade' }),
  flowRunId: text('flow_run_id').notNull().references(() => flowRuns.id, { onDelete: 'cascade' }),
  toolId: text('tool_id').notNull(),
  toolName: text('tool_name').notNull(),
  iteration: integer('iteration').notNull(),
  input: json('input').$type<JSONValue>().notNull(),
  output: json('output').$type<JSONValue>(),
  error: text('error'),
  success: boolean('success').notNull(),
  startedAt: timestamp('started_at').notNull().defaultNow(),
  completedAt: timestamp('completed_at'),
  duration: integer('duration'),
});

export const userRelations = relations(user, ({ many }) => ({
  account: many(account),
  session: many(session),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));

export const flowsRelations = relations(flows, ({ many }) => ({
  flowAccess: many(flowAccess),
  flowTriggers: many(flowTriggers),
  flowVersions: many(flowVersions),
  chatMessages: many(chatMessages),
  flowRuns: many(flowRuns),
}));

export const flowAccessRelations = relations(flowAccess, ({ one }) => ({
  flow: one(flows, { fields: [flowAccess.flowId], references: [flows.id] }),
}));

export const flowTriggersRelations = relations(flowTriggers, ({ one }) => ({
  flow: one(flows, { fields: [flowTriggers.flowId], references: [flows.id] }),
}));

export const flowVersionsRelations = relations(flowVersions, ({ one }) => ({
  flow: one(flows, { fields: [flowVersions.flowId], references: [flows.id] }),
}));

export const chatMessagesRelations = relations(chatMessages, ({ one }) => ({
  flow: one(flows, { fields: [chatMessages.flowId], references: [flows.id] }),
}));

export const flowRunsRelations = relations(flowRuns, ({ one, many }) => ({
  flow: one(flows, { fields: [flowRuns.flowId], references: [flows.id] }),
  nodeExecutions: many(nodeExecutions),
  batchJobs: many(batchJobs),
  agentToolExecutions: many(agentToolExecutions),
}));

export const nodeExecutionsRelations = relations(nodeExecutions, ({ one, many }) => ({
  flowRun: one(flowRuns, { fields: [nodeExecutions.flowRunId], references: [flowRuns.id] }),
  agentToolExecutions: many(agentToolExecutions),
}));

export const batchJobsRelations = relations(batchJobs, ({ one }) => ({
  flowRun: one(flowRuns, { fields: [batchJobs.flowRunId], references: [flowRuns.id] }),
}));

export const agentToolExecutionsRelations = relations(agentToolExecutions, ({ one }) => ({
  nodeExecution: one(nodeExecutions, { fields: [agentToolExecutions.nodeExecutionId], references: [nodeExecutions.id] }),
  flowRun: one(flowRuns, { fields: [agentToolExecutions.flowRunId], references: [flowRuns.id] }),
}));


export type User = typeof user.$inferSelect;
export type NewUser = typeof user.$inferInsert;
export type Account = typeof account.$inferSelect;
export type NewAccount = typeof account.$inferInsert;
export type Session = typeof session.$inferSelect;
export type NewSession = typeof session.$inferInsert;
export type Verification = typeof verification.$inferSelect;
export type NewVerification = typeof verification.$inferInsert;
export type Credentials = typeof credentials.$inferSelect;
export type NewCredentials = typeof credentials.$inferInsert;
export type Flows = typeof flows.$inferSelect;
export type NewFlows = typeof flows.$inferInsert;
export type RbacTeams = typeof rbacTeams.$inferSelect;
export type NewRbacTeams = typeof rbacTeams.$inferInsert;
export type RbacTeamMembers = typeof rbacTeamMembers.$inferSelect;
export type NewRbacTeamMembers = typeof rbacTeamMembers.$inferInsert;
export type RbacScopeAccess = typeof rbacScopeAccess.$inferSelect;
export type NewRbacScopeAccess = typeof rbacScopeAccess.$inferInsert;
export type FlowAccess = typeof flowAccess.$inferSelect;
export type NewFlowAccess = typeof flowAccess.$inferInsert;
export type FlowTriggers = typeof flowTriggers.$inferSelect;
export type NewFlowTriggers = typeof flowTriggers.$inferInsert;
export type FlowVersions = typeof flowVersions.$inferSelect;
export type NewFlowVersions = typeof flowVersions.$inferInsert;
export type ChatMessages = typeof chatMessages.$inferSelect;
export type NewChatMessages = typeof chatMessages.$inferInsert;
export type FlowRuns = typeof flowRuns.$inferSelect;
export type NewFlowRuns = typeof flowRuns.$inferInsert;
export type NodeExecutions = typeof nodeExecutions.$inferSelect;
export type NewNodeExecutions = typeof nodeExecutions.$inferInsert;
export type BatchJobs = typeof batchJobs.$inferSelect;
export type NewBatchJobs = typeof batchJobs.$inferInsert;
export type AgentToolExecutions = typeof agentToolExecutions.$inferSelect;
export type NewAgentToolExecutions = typeof agentToolExecutions.$inferInsert;
