/**
 * Prisma Schema Generator
 *
 * Converts the merged abstract schema (core + plugins) into Prisma schema
 * model blocks. Unlike the Drizzle generators which produce complete
 * TypeScript files, this generates Prisma DSL.
 *
 * Two modes:
 * 1. `generatePrismaModels(schema, provider)` — returns only the model blocks
 *    (for appending to an existing schema.prisma)
 * 2. `generateFullPrismaSchema(schema, provider)` — returns a complete
 *    schema.prisma including generator + datasource blocks
 *
 * Uses the abstract schema types directly, converting to Prisma's type system:
 *
 * | Abstract    | Prisma (PG/MySQL) | Prisma (SQLite)  |
 * |-------------|-------------------|------------------|
 * | "string"    | String            | String           |
 * | "text"      | String            | String           |
 * | "number"    | Int               | Int              |
 * | "boolean"   | Boolean           | Boolean          |
 * | "date"      | DateTime          | DateTime         |
 * | "json"      | Json              | String           |
 * | "uuid"      | String            | String           |
 * | "bigint"    | BigInt            | BigInt           |
 * | string[]    | enum              | String (fallback)|
 */

import type { PluginFieldAttribute, PluginFieldType } from 'src/types/plugin.types';
import type { MergedSchema, MergedTable } from './schema-merger';

export type PrismaProvider = 'postgresql' | 'mysql' | 'sqlite';

// =============================================================================
// Full Schema Generator
// =============================================================================

/**
 * Generate a complete Prisma schema file from the merged abstract schema.
 *
 * Includes generator, datasource, enums, and all models.
 */
export function generateFullPrismaSchema(schema: MergedSchema, provider: PrismaProvider): string {
  const lines: string[] = [];

  // Header
  lines.push(`// Prisma schema for Invect — AUTO-GENERATED by @invect/cli`);
  lines.push(
    `// Do not edit the Invect models manually. Run \`npx invect-cli generate\` to regenerate.`,
  );
  lines.push(``);

  // Generator block
  lines.push(`generator client {`);
  lines.push(`  provider = "prisma-client-js"`);
  lines.push(`}`);
  lines.push(``);

  // Datasource block
  lines.push(`datasource db {`);
  lines.push(`  provider = "${provider}"`);
  if (provider === 'sqlite') {
    lines.push(`  url      = "file:./dev.db"`);
  } else {
    lines.push(`  url      = env("DATABASE_URL")`);
  }
  lines.push(`}`);
  lines.push(``);

  // Enums (PostgreSQL and MySQL support enums; SQLite doesn't)
  if (provider !== 'sqlite') {
    const enums = collectPrismaEnums(schema);
    if (enums.length > 0) {
      lines.push(
        `// =============================================================================`,
      );
      lines.push(`// Enums`);
      lines.push(
        `// =============================================================================`,
      );
      lines.push(``);
      for (const e of enums) {
        lines.push(`enum ${e.name} {`);
        for (const v of e.values) {
          lines.push(`  ${v}`);
        }
        lines.push(`}`);
        lines.push(``);
      }
    }
  }

  // Models
  lines.push(`// =============================================================================`);
  lines.push(`// Models`);
  lines.push(`// =============================================================================`);
  lines.push(``);

  for (const table of schema.tables) {
    lines.push(generatePrismaModel(table, schema, provider));
    lines.push(``);
  }

  return lines.join('\n');
}

// =============================================================================
// Model-Only Generator (for appending to existing schemas)
// =============================================================================

/**
 * Generate only the Prisma model blocks (no generator/datasource).
 *
 * Useful when adding Invect models to an existing Prisma schema.
 */
export function generatePrismaModels(schema: MergedSchema, provider: PrismaProvider): string {
  const lines: string[] = [];

  lines.push(``);
  lines.push(`// =============================================================================`);
  lines.push(`// Invect Models — AUTO-GENERATED by @invect/cli`);
  lines.push(
    `// Do not edit these models manually. Run \`npx invect-cli generate\` to regenerate.`,
  );
  lines.push(`// =============================================================================`);
  lines.push(``);

  // Enums
  if (provider !== 'sqlite') {
    const enums = collectPrismaEnums(schema);
    for (const e of enums) {
      lines.push(`enum ${e.name} {`);
      for (const v of e.values) {
        lines.push(`  ${v}`);
      }
      lines.push(`}`);
      lines.push(``);
    }
  }

  // Models
  for (const table of schema.tables) {
    lines.push(generatePrismaModel(table, schema, provider));
    lines.push(``);
  }

  return lines.join('\n');
}

// =============================================================================
// Single Model Generator
// =============================================================================

function generatePrismaModel(
  table: MergedTable,
  schema: MergedSchema,
  provider: PrismaProvider,
): string {
  const lines: string[] = [];
  const { name, definition } = table;
  const dbTableName = definition.tableName || toSnakeCase(name);
  const modelName = capitalize(name);

  lines.push(`model ${modelName} {`);

  // Fields
  for (const [fieldName, field] of Object.entries(definition.fields)) {
    const dbColName = toSnakeCase(fieldName);
    const prismaType = getPrismaType(field, provider, name, fieldName);
    const attrs = getPrismaAttributes(fieldName, dbColName, field, provider);

    lines.push(`  ${fieldName}  ${prismaType}${attrs}`);
  }

  // Relation fields (Prisma requires explicit relation fields)
  const relationLines = generateRelationFields(table, schema, provider);
  for (const line of relationLines) {
    lines.push(`  ${line}`);
  }

  // Composite primary key
  if (definition.compositePrimaryKey?.length) {
    lines.push(``);
    lines.push(`  @@id([${definition.compositePrimaryKey.join(', ')}])`);
  }

  // @@index for indexed fields
  for (const [fieldName, field] of Object.entries(definition.fields)) {
    if (field.index && !field.unique && !field.primaryKey) {
      lines.push(`  @@index([${fieldName}])`);
    }
  }

  // @@map for table name mapping
  if (dbTableName !== name) {
    lines.push(`  @@map("${dbTableName}")`);
  }

  lines.push(`}`);

  return lines.join('\n');
}

// =============================================================================
// Type Mapping
// =============================================================================

function getPrismaType(
  field: PluginFieldAttribute,
  provider: PrismaProvider,
  tableName: string,
  fieldName: string,
): string {
  const optional = field.required === false ? '?' : '';

  if (isEnumType(field.type)) {
    if (provider === 'sqlite') {
      // SQLite doesn't support enums in Prisma, use String
      return `String${optional}`;
    }
    const enumName = prismaEnumName(tableName, fieldName);
    return `${enumName}${optional}`;
  }

  switch (field.type) {
    case 'string':
    case 'text':
    case 'uuid':
      return `String${optional}`;
    case 'number':
      return `Int${optional}`;
    case 'bigint':
      return `BigInt${optional}`;
    case 'boolean':
      return `Boolean${optional}`;
    case 'date':
      return `DateTime${optional}`;
    case 'json':
      // SQLite doesn't have native JSON in Prisma — use String
      if (provider === 'sqlite') {
        return `String${optional}`;
      }
      return `Json${optional}`;
    default:
      return `String${optional}`;
  }
}

// =============================================================================
// Attribute Generation
// =============================================================================

function getPrismaAttributes(
  fieldName: string,
  dbColName: string,
  field: PluginFieldAttribute,
  provider: PrismaProvider,
): string {
  const attrs: string[] = [];

  // @id (single-column PK)
  if (field.primaryKey) {
    attrs.push('@id');
  }

  // @unique
  if (field.unique) {
    attrs.push('@unique');
  }

  // @default
  if (field.defaultValue !== undefined) {
    const defaultAttr = getPrismaDefault(field.defaultValue, field.type, provider);
    if (defaultAttr) {
      attrs.push(defaultAttr);
    }
  }

  // @updatedAt (for date fields with "now()" default and name "updatedAt")
  // In Prisma, @updatedAt automatically updates the timestamp
  // We only add it if the field is named updatedAt
  if (fieldName === 'updatedAt' && field.type === 'date') {
    attrs.push('@updatedAt');
  }

  // @map (column name differs from field name)
  if (dbColName !== fieldName) {
    attrs.push(`@map("${dbColName}")`);
  }

  // @db.Text for MySQL long strings
  if (provider === 'mysql' && field.type === 'text') {
    attrs.push('@db.Text');
  }

  // @db.Timestamptz for PostgreSQL dates
  if (provider === 'postgresql' && field.type === 'date') {
    attrs.push('@db.Timestamptz(3)');
  }

  if (attrs.length === 0) {
    return '';
  }
  return '  ' + attrs.join(' ');
}

function getPrismaDefault(
  value: string | number | boolean | 'uuid()' | 'now()',
  _type: PluginFieldType,
  _provider: PrismaProvider,
): string | null {
  if (value === 'uuid()') {
    return '@default(uuid())';
  }
  if (value === 'now()') {
    return '@default(now())';
  }
  if (typeof value === 'boolean') {
    return `@default(${value})`;
  }
  if (typeof value === 'number') {
    return `@default(${value})`;
  }
  if (typeof value === 'string') {
    return `@default("${value}")`;
  }
  return null;
}

// =============================================================================
// Relation Fields
// =============================================================================

/**
 * Generate Prisma relation fields for a model.
 *
 * In Prisma, if model A has a FK `bId → B.id`, we need:
 *   - On A: `b B @relation(fields: [bId], references: [id])`
 *   - On B: `as A[]` (reverse side)
 *
 * We generate the "one" side (FK holder) here; the "many" side
 * (reverse) is added to the referenced model.
 */
function generateRelationFields(
  table: MergedTable,
  schema: MergedSchema,
  _provider: PrismaProvider,
): string[] {
  const lines: string[] = [];
  const { definition } = table;

  // One-side: this table has FKs
  for (const [fieldName, field] of Object.entries(definition.fields)) {
    if (!field.references) {
      continue;
    }

    const refTableLogical = findLogicalName(schema, field.references.table);
    const refModelName = capitalize(refTableLogical);
    const relName = fieldName.replace(/Id$/, '').replace(/_id$/, '');
    const onDelete = mapOnDelete(field.references.onDelete);

    lines.push(
      `${relName}  ${refModelName}  @relation(fields: [${fieldName}], references: [${field.references.field}], onDelete: ${onDelete})`,
    );
  }

  // Many-side: other tables have FKs pointing to this table
  for (const otherTable of schema.tables) {
    if (otherTable.name === table.name) {
      continue;
    }

    for (const [_fieldName, field] of Object.entries(otherTable.definition.fields)) {
      if (!field.references) {
        continue;
      }

      // Check if this FK references our table
      const refsOurTable =
        field.references.table === table.name ||
        field.references.table === (table.definition.tableName || toSnakeCase(table.name));

      if (refsOurTable) {
        const otherModelName = capitalize(otherTable.name);
        // If the FK is unique, this is a one-to-one relation (singular, optional)
        // Otherwise it's one-to-many (array)
        const isUnique = field.unique === true;
        const relName = otherTable.name;
        lines.push(`${relName}  ${otherModelName}${isUnique ? '?' : '[]'}`);
      }
    }
  }

  return lines;
}

function mapOnDelete(onDelete?: string): string {
  switch (onDelete) {
    case 'cascade':
      return 'Cascade';
    case 'set null':
      return 'SetNull';
    case 'restrict':
      return 'Restrict';
    case 'no action':
      return 'NoAction';
    default:
      return 'NoAction';
  }
}

// =============================================================================
// Enum Helpers
// =============================================================================

interface PrismaEnumDef {
  name: string;
  values: string[];
}

function collectPrismaEnums(schema: MergedSchema): PrismaEnumDef[] {
  const enums: PrismaEnumDef[] = [];

  for (const table of schema.tables) {
    for (const [fieldName, field] of Object.entries(table.definition.fields)) {
      if (isEnumType(field.type)) {
        enums.push({
          name: prismaEnumName(table.name, fieldName),
          values: field.type,
        });
      }
    }
  }

  return enums;
}

function prismaEnumName(tableName: string, fieldName: string): string {
  return `${capitalize(tableName)}${capitalize(fieldName)}`;
}

// =============================================================================
// Shared Utilities
// =============================================================================

function isEnumType(type: PluginFieldType): type is string[] {
  return Array.isArray(type);
}

function toSnakeCase(str: string): string {
  return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

/**
 * Find the logical (camelCase) table name from a DB table name.
 */
function findLogicalName(schema: MergedSchema, tableRef: string): string {
  // First try exact match on logical name
  const exact = schema.tables.find((t) => t.name === tableRef);
  if (exact) {
    return exact.name;
  }

  // Try by tableName property
  const byDbName = schema.tables.find(
    (t) => t.definition.tableName === tableRef || toSnakeCase(t.name) === tableRef,
  );
  if (byDbName) {
    return byDbName.name;
  }

  // Fallback: convert to camelCase
  if (tableRef.includes('_')) {
    return tableRef.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
  }
  return tableRef;
}
