/**
 * Drizzle Schema Generators
 *
 * Converts the merged abstract schema (core + plugins) into three
 * dialect-specific Drizzle ORM schema files as TypeScript source code.
 *
 * Each generator produces a complete, self-contained .ts file that can
 * be used by Drizzle Kit for migration generation.
 */

import type { PluginFieldAttribute, PluginFieldType } from 'src/types/plugin.types';
import type { MergedSchema, MergedTable } from './schema-merger';

// =============================================================================
// Common Utilities
// =============================================================================

/**
 * Convert camelCase to snake_case for DB column names.
 */
function toSnakeCase(str: string): string {
  return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

/**
 * Check if a field type is an enum (string array).
 */
function isEnumType(type: PluginFieldType): type is string[] {
  return Array.isArray(type);
}

/**
 * Generate a variable name for an enum from a table + field.
 * e.g., flowRuns + status → flowRunStatusEnum
 */
function enumVarName(tableName: string, fieldName: string): string {
  return `${tableName}${fieldName.charAt(0).toUpperCase() + fieldName.slice(1)}Enum`;
}

const SQLITE_RUNTIME_DEFAULT_IMPORTS: Record<string, string> = {
  FlowRunStatus: '@invect/core',
  NodeExecutionStatus: '@invect/core',
};

function collectSqliteRuntimeDefaultImports(schema: MergedSchema): Map<string, Set<string>> {
  const importsByModule = new Map<string, Set<string>>();

  for (const table of schema.tables) {
    for (const field of Object.values(table.definition.fields)) {
      if (typeof field.defaultValue !== 'string' || !field.typeAnnotation) {
        continue;
      }

      const importPath = SQLITE_RUNTIME_DEFAULT_IMPORTS[field.typeAnnotation];
      if (!importPath) {
        continue;
      }

      const existing = importsByModule.get(importPath) ?? new Set<string>();
      existing.add(field.typeAnnotation);
      importsByModule.set(importPath, existing);
    }
  }

  return importsByModule;
}

// =============================================================================
// SQLite Generator
// =============================================================================

export function generateSqliteSchema(schema: MergedSchema): string {
  const lines: string[] = [];
  const runtimeImports = collectSqliteRuntimeDefaultImports(schema);

  // Header
  lines.push(`// SQLite schema for Invect — AUTO-GENERATED by @invect/cli`);
  lines.push(`// Do not edit manually. Run \`npx invect-cli generate\` to regenerate.`);
  lines.push(``);
  lines.push(
    `import { sqliteTable, text, integer, primaryKey, type AnySQLiteColumn } from 'drizzle-orm/sqlite-core';`,
  );
  lines.push(`import { relations, sql } from 'drizzle-orm';`);
  for (const [importPath, identifiers] of runtimeImports.entries()) {
    lines.push(`import { ${Array.from(identifiers).sort().join(', ')} } from '${importPath}';`);
  }
  lines.push(`import { randomUUID } from 'crypto';`);
  lines.push(``);
  lines.push(`// Type imports — these are used for $type<>() annotations`);
  lines.push(`import type { JSONValue } from '.';`);
  lines.push(``);

  // Collect all typeAnnotations to generate type imports
  const typeAnnotations = collectTypeAnnotations(schema);
  if (typeAnnotations.size > 0) {
    lines.push(`// Plugin & core type annotations`);
    lines.push(`// You may need to adjust these imports based on your project structure`);
    lines.push(``);
  }

  // Tables
  lines.push(`// =============================================================================`);
  lines.push(`// Tables`);
  lines.push(`// =============================================================================`);
  lines.push(``);

  for (const table of schema.tables) {
    lines.push(generateSqliteTable(table, schema));
    lines.push(``);
  }

  // Relations
  lines.push(`// =============================================================================`);
  lines.push(`// Relations`);
  lines.push(`// =============================================================================`);
  lines.push(``);
  lines.push(generateRelations(schema));

  // Type exports
  lines.push(``);
  lines.push(`// =============================================================================`);
  lines.push(`// Type exports`);
  lines.push(`// =============================================================================`);
  lines.push(``);
  for (const table of schema.tables) {
    const varName = table.name;
    const typeName = capitalize(table.name);
    lines.push(`export type ${typeName} = typeof ${varName}.$inferSelect;`);
    lines.push(`export type New${typeName} = typeof ${varName}.$inferInsert;`);
  }

  return lines.join('\n');
}

function generateSqliteTable(table: MergedTable, schema: MergedSchema): string {
  const lines: string[] = [];
  const { name, definition } = table;
  const dbTableName = definition.tableName || toSnakeCase(name);
  const hasCompositePK = !!definition.compositePrimaryKey?.length;

  lines.push(`export const ${name} = sqliteTable('${dbTableName}', {`);

  for (const [fieldName, field] of Object.entries(definition.fields)) {
    const colName = toSnakeCase(fieldName);
    lines.push(`  ${fieldName}: ${sqliteColumn(fieldName, colName, field, name, schema)},`);
  }

  if (hasCompositePK) {
    const pkCols = (definition.compositePrimaryKey ?? []).map((f) => `table.${f}`).join(', ');
    lines.push(`}, (table) => [primaryKey({ columns: [${pkCols}] })]);`);
  } else {
    lines.push(`});`);
  }

  return lines.join('\n');
}

function sqliteColumn(
  fieldName: string,
  colName: string,
  field: PluginFieldAttribute,
  tableName: string,
  schema?: MergedSchema,
): string {
  let col: string;

  if (isEnumType(field.type)) {
    // SQLite: enums are just text columns
    col = `text('${colName}')`;
  } else {
    switch (field.type) {
      case 'string':
      case 'text':
        col = `text('${colName}')`;
        break;
      case 'uuid':
        col = `text('${colName}')`;
        break;
      case 'number':
      case 'bigint':
        col = `integer('${colName}')`;
        break;
      case 'boolean':
        col = `integer('${colName}', { mode: 'boolean' })`;
        break;
      case 'date':
        col = `text('${colName}')`;
        break;
      case 'json':
        col = `text('${colName}', { mode: 'json' })`;
        break;
      default:
        col = `text('${colName}')`;
    }
  }

  // Type annotation
  if (field.typeAnnotation) {
    col += `.$type<${field.typeAnnotation}>()`;
  }

  // Primary key
  if (field.primaryKey) {
    col += `.primaryKey()`;
  }

  // Not null
  if (field.required !== false) {
    col += `.notNull()`;
  }

  // Unique
  if (field.unique) {
    col += `.unique()`;
  }

  // Default value
  if (field.defaultValue !== undefined) {
    col += sqliteDefault(field.defaultValue, field.type, field.typeAnnotation);
  }

  // Foreign key
  if (field.references) {
    const refTable = findTableVarForDbName(field.references.table, schema);
    const refField = field.references.field;
    const onDelete = field.references.onDelete || 'no action';
    if (refTable === tableName) {
      col += `.references((): AnySQLiteColumn => ${refTable}.${refField}, { onDelete: '${onDelete}' })`;
    } else {
      col += `.references(() => ${refTable}.${refField}, { onDelete: '${onDelete}' })`;
    }
  }

  return col;
}

function sqliteDefault(
  value: string | number | boolean | 'uuid()' | 'now()',
  _type: PluginFieldType,
  typeAnnotation?: string,
): string {
  if (value === 'uuid()') {
    return `.$defaultFn(() => randomUUID())`;
  }
  if (value === 'now()') {
    return `.default(sql\`CURRENT_TIMESTAMP\`)`;
  }
  if (typeof value === 'boolean') {
    return `.default(${value})`;
  }
  if (typeof value === 'number') {
    return `.default(${value})`;
  }
  if (typeof value === 'string') {
    if (typeAnnotation && SQLITE_RUNTIME_DEFAULT_IMPORTS[typeAnnotation]) {
      return `.default(${typeAnnotation}.${value})`;
    }
    return `.default('${value}')`;
  }
  return '';
}

// =============================================================================
// PostgreSQL Generator
// =============================================================================

export function generatePostgresSchema(schema: MergedSchema): string {
  const lines: string[] = [];

  // Header
  lines.push(`// PostgreSQL schema for Invect — AUTO-GENERATED by @invect/cli`);
  lines.push(`// Do not edit manually. Run \`npx invect-cli generate\` to regenerate.`);
  lines.push(``);
  lines.push(`import {`);
  lines.push(`  pgTable,`);
  lines.push(`  text,`);
  lines.push(`  integer,`);
  lines.push(`  boolean,`);
  lines.push(`  timestamp,`);
  lines.push(`  json,`);
  lines.push(`  pgEnum,`);
  lines.push(`  uuid,`);
  lines.push(`  bigint,`);
  lines.push(`  type AnyPgColumn,`);
  lines.push(`  primaryKey,`);
  lines.push(`} from 'drizzle-orm/pg-core';`);
  lines.push(`import { relations } from 'drizzle-orm';`);
  lines.push(`import { randomUUID } from 'crypto';`);
  lines.push(``);
  lines.push(`import type { JSONValue } from '.';`);
  lines.push(``);

  // Enums
  const enums = collectEnums(schema);
  if (enums.length > 0) {
    lines.push(`// =============================================================================`);
    lines.push(`// Enums`);
    lines.push(`// =============================================================================`);
    lines.push(``);
    for (const e of enums) {
      lines.push(
        `export const ${e.varName} = pgEnum('${e.dbName}', [${e.values.map((v) => `'${v}'`).join(', ')}]);`,
      );
    }
    lines.push(``);
  }

  // Tables
  lines.push(`// =============================================================================`);
  lines.push(`// Tables`);
  lines.push(`// =============================================================================`);
  lines.push(``);

  for (const table of schema.tables) {
    lines.push(generatePostgresTable(table, schema, enums));
    lines.push(``);
  }

  // Relations
  lines.push(`// =============================================================================`);
  lines.push(`// Relations`);
  lines.push(`// =============================================================================`);
  lines.push(``);
  lines.push(generateRelations(schema));

  // Type exports
  lines.push(``);
  lines.push(`// =============================================================================`);
  lines.push(`// Type exports`);
  lines.push(`// =============================================================================`);
  lines.push(``);
  for (const table of schema.tables) {
    const typeName = capitalize(table.name);
    lines.push(`export type ${typeName} = typeof ${table.name}.$inferSelect;`);
    lines.push(`export type New${typeName} = typeof ${table.name}.$inferInsert;`);
  }

  return lines.join('\n');
}

function generatePostgresTable(table: MergedTable, schema: MergedSchema, enums: EnumDef[]): string {
  const lines: string[] = [];
  const { name, definition } = table;
  const dbTableName = definition.tableName || toSnakeCase(name);
  const hasCompositePK = !!definition.compositePrimaryKey?.length;

  lines.push(`export const ${name} = pgTable('${dbTableName}', {`);

  for (const [fieldName, field] of Object.entries(definition.fields)) {
    const colName = toSnakeCase(fieldName);
    lines.push(
      `  ${fieldName}: ${postgresColumn(fieldName, colName, field, name, enums, schema)},`,
    );
  }

  if (hasCompositePK) {
    const pkCols = (definition.compositePrimaryKey ?? []).map((f) => `table.${f}`).join(', ');
    lines.push(`}, (table) => [primaryKey({ columns: [${pkCols}] })]);`);
  } else {
    lines.push(`});`);
  }

  return lines.join('\n');
}

function postgresColumn(
  fieldName: string,
  colName: string,
  field: PluginFieldAttribute,
  tableName: string,
  enums: EnumDef[],
  schema?: MergedSchema,
): string {
  let col: string;

  if (isEnumType(field.type)) {
    const eVar = enums.find((e) => e.tableName === tableName && e.fieldName === fieldName)?.varName;
    col = eVar ? `${eVar}('${colName}')` : `text('${colName}')`;
  } else {
    switch (field.type) {
      case 'string':
      case 'text':
        col = `text('${colName}')`;
        break;
      case 'uuid':
        col = `uuid('${colName}')`;
        break;
      case 'number':
        col = `integer('${colName}')`;
        break;
      case 'bigint':
        col = `bigint('${colName}', { mode: 'bigint' })`;
        break;
      case 'boolean':
        col = `boolean('${colName}')`;
        break;
      case 'date':
        col = `timestamp('${colName}')`;
        break;
      case 'json':
        col = `json('${colName}')`;
        break;
      default:
        col = `text('${colName}')`;
    }
  }

  // Type annotation
  if (field.typeAnnotation) {
    col += `.$type<${field.typeAnnotation}>()`;
  }

  // Primary key
  if (field.primaryKey) {
    col += `.primaryKey()`;
  }

  // Not null
  if (field.required !== false) {
    col += `.notNull()`;
  }

  // Unique
  if (field.unique) {
    col += `.unique()`;
  }

  // Default value
  if (field.defaultValue !== undefined) {
    col += postgresDefault(field.defaultValue, field.type);
  }

  // Foreign key
  if (field.references) {
    const refTable = findTableVarForDbName(field.references.table, schema);
    const refField = field.references.field;
    const onDelete = field.references.onDelete || 'no action';
    if (refTable === tableName) {
      col += `.references((): AnyPgColumn => ${refTable}.${refField}, { onDelete: '${onDelete}' })`;
    } else {
      col += `.references(() => ${refTable}.${refField}, { onDelete: '${onDelete}' })`;
    }
  }

  return col;
}

function postgresDefault(
  value: string | number | boolean | 'uuid()' | 'now()',
  _type: PluginFieldType,
): string {
  if (value === 'uuid()') {
    return `.$default(() => randomUUID())`;
  }
  if (value === 'now()') {
    return `.defaultNow()`;
  }
  if (typeof value === 'boolean') {
    return `.default(${value})`;
  }
  if (typeof value === 'number') {
    return `.default(${value})`;
  }
  if (typeof value === 'string') {
    return `.default('${value}')`;
  }
  return '';
}

// =============================================================================
// MySQL Generator
// =============================================================================

export function generateMysqlSchema(schema: MergedSchema): string {
  const lines: string[] = [];

  // Header
  lines.push(`// MySQL schema for Invect — AUTO-GENERATED by @invect/cli`);
  lines.push(`// Do not edit manually. Run \`npx invect-cli generate\` to regenerate.`);
  lines.push(``);
  lines.push(`import {`);
  lines.push(`  mysqlTable,`);
  lines.push(`  varchar,`);
  lines.push(`  text,`);
  lines.push(`  int,`);
  lines.push(`  bigint,`);
  lines.push(`  boolean,`);
  lines.push(`  timestamp,`);
  lines.push(`  json,`);
  lines.push(`  mysqlEnum,`);
  lines.push(`  type AnyMySqlColumn,`);
  lines.push(`  primaryKey,`);
  lines.push(`} from 'drizzle-orm/mysql-core';`);
  lines.push(`import { relations, sql } from 'drizzle-orm';`);
  lines.push(`import { randomUUID } from 'crypto';`);
  lines.push(``);
  lines.push(`import type { JSONValue } from '.';`);
  lines.push(``);

  // Tables
  lines.push(`// =============================================================================`);
  lines.push(`// Tables`);
  lines.push(`// =============================================================================`);
  lines.push(``);

  for (const table of schema.tables) {
    lines.push(generateMysqlTable(table, schema));
    lines.push(``);
  }

  // Relations
  lines.push(`// =============================================================================`);
  lines.push(`// Relations`);
  lines.push(`// =============================================================================`);
  lines.push(``);
  lines.push(generateRelations(schema));

  // Type exports
  lines.push(``);
  lines.push(`// =============================================================================`);
  lines.push(`// Type exports`);
  lines.push(`// =============================================================================`);
  lines.push(``);
  for (const table of schema.tables) {
    const typeName = capitalize(table.name);
    lines.push(`export type ${typeName} = typeof ${table.name}.$inferSelect;`);
    lines.push(`export type New${typeName} = typeof ${table.name}.$inferInsert;`);
  }

  return lines.join('\n');
}

function generateMysqlTable(table: MergedTable, schema: MergedSchema): string {
  // schema is used by mysqlColumn for FK reference resolution
  const lines: string[] = [];
  const { name, definition } = table;
  const dbTableName = definition.tableName || toSnakeCase(name);
  const hasCompositePK = !!definition.compositePrimaryKey?.length;

  lines.push(`export const ${name} = mysqlTable('${dbTableName}', {`);

  for (const [fieldName, field] of Object.entries(definition.fields)) {
    const colName = toSnakeCase(fieldName);
    lines.push(`  ${fieldName}: ${mysqlColumn(fieldName, colName, field, name, schema)},`);
  }

  if (hasCompositePK) {
    const pkCols = (definition.compositePrimaryKey ?? []).map((f) => `table.${f}`).join(', ');
    lines.push(`}, (table) => [primaryKey({ columns: [${pkCols}] })]);`);
  } else {
    lines.push(`});`);
  }

  return lines.join('\n');
}

function mysqlColumn(
  fieldName: string,
  colName: string,
  field: PluginFieldAttribute,
  tableName: string,
  schema?: MergedSchema,
): string {
  const maxLen = field.maxLength ?? 255;
  let col: string;

  if (isEnumType(field.type)) {
    const enumValues = field.type.map((v) => `'${v}'`).join(', ');
    col = `mysqlEnum('${colName}', [${enumValues}])`;
  } else {
    switch (field.type) {
      case 'string':
        col = `varchar('${colName}', { length: ${maxLen} })`;
        break;
      case 'text':
        col = `text('${colName}')`;
        break;
      case 'uuid':
        col = `varchar('${colName}', { length: 36 })`;
        break;
      case 'number':
        col = `int('${colName}')`;
        break;
      case 'bigint':
        col = `bigint('${colName}', { mode: 'bigint' })`;
        break;
      case 'boolean':
        col = `boolean('${colName}')`;
        break;
      case 'date':
        col = `timestamp('${colName}')`;
        break;
      case 'json':
        col = `json('${colName}')`;
        break;
      default:
        col = `varchar('${colName}', { length: ${maxLen} })`;
    }
  }

  // Type annotation
  if (field.typeAnnotation) {
    col += `.$type<${field.typeAnnotation}>()`;
  }

  // Primary key
  if (field.primaryKey) {
    col += `.primaryKey()`;
  }

  // Not null
  if (field.required !== false) {
    col += `.notNull()`;
  }

  // Unique
  if (field.unique) {
    col += `.unique()`;
  }

  // Default value
  if (field.defaultValue !== undefined) {
    col += mysqlDefault(field.defaultValue, field.type);
  }

  // Foreign key
  if (field.references) {
    const refTable = findTableVarForDbName(field.references.table, schema);
    const refField = field.references.field;
    const onDelete = field.references.onDelete || 'no action';
    if (refTable === tableName) {
      col += `.references((): AnyMySqlColumn => ${refTable}.${refField}, { onDelete: '${onDelete}' })`;
    } else {
      col += `.references(() => ${refTable}.${refField}, { onDelete: '${onDelete}' })`;
    }
  }

  return col;
}

function mysqlDefault(
  value: string | number | boolean | 'uuid()' | 'now()',
  _type: PluginFieldType,
): string {
  if (value === 'uuid()') {
    return `.$defaultFn(() => randomUUID())`;
  }
  if (value === 'now()') {
    return `.default(sql\`CURRENT_TIMESTAMP\`)`;
  }
  if (typeof value === 'boolean') {
    return `.default(${value})`;
  }
  if (typeof value === 'number') {
    return `.default(${value})`;
  }
  if (typeof value === 'string') {
    return `.default('${value}')`;
  }
  return '';
}

// =============================================================================
// Append-mode Generators
// =============================================================================
//
// These produce only the table definitions, relations, and type exports
// for appending to an existing Drizzle schema file. They include:
//   - A commented section marker
//   - Additional imports needed (inserted at top when used by CLI)
//   - Table definitions
//   - Relations
//   - Type exports
//
// The CLI handles merging the import lines into the existing file.
// This approach mirrors how better-auth generates schema code that can
// be appended to the user's existing schema file.

export interface AppendSchemaResult {
  /** Import statements that need to be added (CLI merges these) */
  imports: string[];
  /** Table + relation + type code to append */
  code: string;
}

export function generateSqliteSchemaAppend(schema: MergedSchema): AppendSchemaResult {
  const runtimeImports = collectSqliteRuntimeDefaultImports(schema);
  const imports = [
    `import { sqliteTable, text, integer, primaryKey, type AnySQLiteColumn } from 'drizzle-orm/sqlite-core';`,
    `import { relations, sql } from 'drizzle-orm';`,
    `import { randomUUID } from 'crypto';`,
  ];

  for (const [importPath, identifiers] of runtimeImports.entries()) {
    imports.push(`import { ${Array.from(identifiers).sort().join(', ')} } from '${importPath}';`);
  }

  const lines: string[] = [];
  lines.push(``);
  lines.push(`// =============================================================================`);
  lines.push(`// Invect tables — AUTO-GENERATED by @invect/cli`);
  lines.push(`// Do not edit below this line. Run \`npx invect-cli generate\` to regenerate.`);
  lines.push(`// =============================================================================`);
  lines.push(``);

  for (const table of schema.tables) {
    lines.push(generateSqliteTable(table, schema));
    lines.push(``);
  }

  lines.push(generateRelations(schema));
  lines.push(``);

  for (const table of schema.tables) {
    const typeName = capitalize(table.name);
    lines.push(`export type ${typeName} = typeof ${table.name}.$inferSelect;`);
    lines.push(`export type New${typeName} = typeof ${table.name}.$inferInsert;`);
  }

  return { imports, code: lines.join('\n') };
}

export function generatePostgresSchemaAppend(schema: MergedSchema): AppendSchemaResult {
  const imports = [
    `import { pgTable, text, integer, boolean, timestamp, json, pgEnum, uuid, bigint, primaryKey, type AnyPgColumn } from 'drizzle-orm/pg-core';`,
    `import { relations } from 'drizzle-orm';`,
    `import { randomUUID } from 'crypto';`,
  ];

  const lines: string[] = [];
  lines.push(``);
  lines.push(`// =============================================================================`);
  lines.push(`// Invect tables — AUTO-GENERATED by @invect/cli`);
  lines.push(`// Do not edit below this line. Run \`npx invect-cli generate\` to regenerate.`);
  lines.push(`// =============================================================================`);
  lines.push(``);

  const enums = collectEnums(schema);
  if (enums.length > 0) {
    for (const e of enums) {
      lines.push(
        `export const ${e.varName} = pgEnum('${e.dbName}', [${e.values.map((v) => `'${v}'`).join(', ')}]);`,
      );
    }
    lines.push(``);
  }

  for (const table of schema.tables) {
    lines.push(generatePostgresTable(table, schema, enums));
    lines.push(``);
  }

  lines.push(generateRelations(schema));
  lines.push(``);

  for (const table of schema.tables) {
    const typeName = capitalize(table.name);
    lines.push(`export type ${typeName} = typeof ${table.name}.$inferSelect;`);
    lines.push(`export type New${typeName} = typeof ${table.name}.$inferInsert;`);
  }

  return { imports, code: lines.join('\n') };
}

export function generateMysqlSchemaAppend(schema: MergedSchema): AppendSchemaResult {
  const imports = [
    `import { mysqlTable, varchar, text, int, bigint, boolean, timestamp, json, mysqlEnum, primaryKey, type AnyMySqlColumn } from 'drizzle-orm/mysql-core';`,
    `import { relations, sql } from 'drizzle-orm';`,
    `import { randomUUID } from 'crypto';`,
  ];

  const lines: string[] = [];
  lines.push(``);
  lines.push(`// =============================================================================`);
  lines.push(`// Invect tables — AUTO-GENERATED by @invect/cli`);
  lines.push(`// Do not edit below this line. Run \`npx invect-cli generate\` to regenerate.`);
  lines.push(`// =============================================================================`);
  lines.push(``);

  for (const table of schema.tables) {
    lines.push(generateMysqlTable(table, schema));
    lines.push(``);
  }

  lines.push(generateRelations(schema));
  lines.push(``);

  for (const table of schema.tables) {
    const typeName = capitalize(table.name);
    lines.push(`export type ${typeName} = typeof ${table.name}.$inferSelect;`);
    lines.push(`export type New${typeName} = typeof ${table.name}.$inferInsert;`);
  }

  return { imports, code: lines.join('\n') };
}

// =============================================================================
// Relation Generator (shared across dialects)
// =============================================================================

function generateRelations(schema: MergedSchema): string {
  const lines: string[] = [];

  // Build a map of FK references: which tables reference which
  const refs: { from: string; fromField: string; to: string; toField: string }[] = [];

  for (const table of schema.tables) {
    for (const [fieldName, field] of Object.entries(table.definition.fields)) {
      if (field.references) {
        const toTableVar = findTableVarForDbName(field.references.table, schema);
        refs.push({
          from: table.name,
          fromField: fieldName,
          to: toTableVar,
          toField: field.references.field,
        });
      }
    }
  }

  for (const table of schema.tables) {
    // Find "one" relations (this table has FK → other table)
    const oneRels = refs.filter((r) => r.from === table.name);
    // Find "many" relations (other tables have FK → this table)
    const manyRels = refs.filter((r) => r.to === table.name);

    if (oneRels.length === 0 && manyRels.length === 0) {
      continue;
    }

    const relParts: string[] = [];
    const destructure: string[] = [];

    if (oneRels.length > 0) {
      destructure.push('one');
    }
    if (manyRels.length > 0) {
      destructure.push('many');
    }

    for (const rel of oneRels) {
      // Derive a relation name from the FK field: "flowId" → "flow"
      const relName = rel.fromField.replace(/Id$/, '').replace(/(_id)$/, '');
      relParts.push(
        `  ${relName}: one(${rel.to}, { fields: [${table.name}.${rel.fromField}], references: [${rel.to}.${rel.toField}] }),`,
      );
    }

    for (const rel of manyRels) {
      // Derive a relation name from the source table
      const relName = rel.from;
      // Avoid duplicates (e.g., multiple FKs from same table)
      relParts.push(`  ${relName}: many(${rel.from}),`);
    }

    lines.push(
      `export const ${table.name}Relations = relations(${table.name}, ({ ${destructure.join(', ')} }) => ({`,
    );
    lines.push(relParts.join('\n'));
    lines.push(`}));`);
    lines.push(``);
  }

  return lines.join('\n');
}

// =============================================================================
// Enum Collection
// =============================================================================

interface EnumDef {
  varName: string;
  dbName: string;
  values: string[];
  tableName: string;
  fieldName: string;
}

function collectEnums(schema: MergedSchema): EnumDef[] {
  const enums: EnumDef[] = [];

  for (const table of schema.tables) {
    for (const [fieldName, field] of Object.entries(table.definition.fields)) {
      if (isEnumType(field.type)) {
        const varName = enumVarName(table.name, fieldName);
        const dbName = `${toSnakeCase(table.name)}_${toSnakeCase(fieldName)}`;
        enums.push({
          varName,
          dbName,
          values: field.type,
          tableName: table.name,
          fieldName,
        });
      }
    }
  }

  return enums;
}

// =============================================================================
// Type Annotation Collection
// =============================================================================

function collectTypeAnnotations(schema: MergedSchema): Set<string> {
  const annotations = new Set<string>();
  for (const table of schema.tables) {
    for (const field of Object.values(table.definition.fields)) {
      if (field.typeAnnotation) {
        annotations.add(field.typeAnnotation);
      }
    }
  }
  return annotations;
}

// =============================================================================
// Shared Helpers
// =============================================================================

/**
 * Build a map from DB table name → JS variable name from the schema.
 */
function buildTableMap(schema: MergedSchema): Map<string, string> {
  const map = new Map<string, string>();
  for (const table of schema.tables) {
    const dbName = table.definition.tableName || toSnakeCase(table.name);
    map.set(dbName, table.name);
    // Also map by logical name for convenience
    map.set(table.name, table.name);
  }
  return map;
}

/**
 * Find the JS variable name for a given DB table name.
 * Uses the schema to do a proper lookup (e.g., 'execution_traces' → 'nodeExecutions').
 * Falls back to camelCase heuristic if no schema provided.
 */
function findTableVarForDbName(dbName: string, schema?: MergedSchema): string {
  if (schema) {
    const tableMap = buildTableMap(schema);
    const found = tableMap.get(dbName);
    if (found) {
      return found;
    }
  }
  // Fallback: convert snake_case to camelCase
  if (dbName.includes('_')) {
    return dbName.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
  }
  return dbName;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// =============================================================================
// Raw SQL Generators
// =============================================================================

/**
 * Generate raw SQL CREATE TABLE statements for SQLite.
 */
export function generateSqliteRawSql(schema: MergedSchema): string {
  const lines: string[] = [];
  lines.push(`-- SQLite migration for Invect — AUTO-GENERATED by @invect/cli`);
  lines.push(`-- Run against your SQLite database to create the required tables.`);
  lines.push(``);

  for (const table of schema.tables) {
    lines.push(generateRawSqlTable(table, 'sqlite'));
    lines.push(``);
  }

  return lines.join('\n');
}

/**
 * Generate raw SQL CREATE TABLE statements for PostgreSQL.
 */
export function generatePostgresRawSql(schema: MergedSchema): string {
  const lines: string[] = [];
  lines.push(`-- PostgreSQL migration for Invect — AUTO-GENERATED by @invect/cli`);
  lines.push(`-- Run against your PostgreSQL database to create the required tables.`);
  lines.push(``);

  // Collect enums for PostgreSQL
  for (const table of schema.tables) {
    for (const [fieldName, field] of Object.entries(table.definition.fields)) {
      if (isEnumType(field.type)) {
        const eName = `${table.definition.tableName || toSnakeCase(table.name)}_${toSnakeCase(fieldName)}`;
        lines.push(`CREATE TYPE ${eName} AS ENUM (${field.type.map((v) => `'${v}'`).join(', ')});`);
      }
    }
  }
  if (lines.length > 3) {
    lines.push(``);
  }

  for (const table of schema.tables) {
    lines.push(generateRawSqlTable(table, 'postgresql'));
    lines.push(``);
  }

  return lines.join('\n');
}

/**
 * Generate raw SQL CREATE TABLE statements for MySQL.
 */
export function generateMysqlRawSql(schema: MergedSchema): string {
  const lines: string[] = [];
  lines.push(`-- MySQL migration for Invect — AUTO-GENERATED by @invect/cli`);
  lines.push(`-- Run against your MySQL database to create the required tables.`);
  lines.push(``);

  for (const table of schema.tables) {
    lines.push(generateRawSqlTable(table, 'mysql'));
    lines.push(``);
  }

  return lines.join('\n');
}

function generateRawSqlTable(
  table: MergedTable,
  dialect: 'sqlite' | 'postgresql' | 'mysql',
): string {
  const lines: string[] = [];
  const { definition } = table;
  const dbTableName = definition.tableName || toSnakeCase(table.name);
  const hasCompositePK = !!definition.compositePrimaryKey?.length;

  lines.push(`CREATE TABLE IF NOT EXISTS ${quoteIdent(dbTableName, dialect)} (`);

  const colDefs: string[] = [];
  const constraints: string[] = [];

  for (const [fieldName, field] of Object.entries(definition.fields)) {
    const colName = toSnakeCase(fieldName);
    const colType = rawSqlColumnType(field, dialect, dbTableName, colName);
    let colDef = `  ${quoteIdent(colName, dialect)} ${colType}`;

    if (field.primaryKey && !hasCompositePK) {
      colDef += ' PRIMARY KEY';
    }
    if (field.required !== false && !field.primaryKey) {
      colDef += ' NOT NULL';
    }
    if (field.unique) {
      colDef += ' UNIQUE';
    }
    const def = rawSqlDefault(field, dialect);
    if (def) {
      colDef += ` DEFAULT ${def}`;
    }
    if (field.references) {
      const refTableName = field.references.table;
      const refField = toSnakeCase(field.references.field);
      const onDelete = (field.references.onDelete || 'NO ACTION').toUpperCase().replace('_', ' ');
      constraints.push(
        `  FOREIGN KEY (${quoteIdent(colName, dialect)}) REFERENCES ${quoteIdent(refTableName, dialect)}(${quoteIdent(refField, dialect)}) ON DELETE ${onDelete}`,
      );
    }
    colDefs.push(colDef);
  }

  if (hasCompositePK) {
    const pkCols = (definition.compositePrimaryKey ?? [])
      .map((f) => quoteIdent(toSnakeCase(f), dialect))
      .join(', ');
    constraints.push(`  PRIMARY KEY (${pkCols})`);
  }

  const allParts = [...colDefs, ...constraints];
  lines.push(allParts.join(',\n'));
  lines.push(`);`);

  return lines.join('\n');
}

function quoteIdent(name: string, dialect: 'sqlite' | 'postgresql' | 'mysql'): string {
  if (dialect === 'mysql') {
    return `\`${name}\``;
  }
  return `"${name}"`;
}

function rawSqlColumnType(
  field: PluginFieldAttribute,
  dialect: 'sqlite' | 'postgresql' | 'mysql',
  tableName: string,
  colName: string,
): string {
  if (isEnumType(field.type)) {
    if (dialect === 'sqlite') {
      return 'TEXT';
    }
    if (dialect === 'postgresql') {
      return `${tableName}_${colName}`;
    }
    // MySQL inline enum
    return `ENUM(${field.type.map((v) => `'${v}'`).join(', ')})`;
  }

  const typeMap: Record<string, Record<string, string>> = {
    sqlite: {
      string: 'TEXT',
      text: 'TEXT',
      uuid: 'TEXT',
      number: 'INTEGER',
      bigint: 'INTEGER',
      boolean: 'INTEGER',
      date: 'TEXT',
      json: 'TEXT',
    },
    postgresql: {
      string: 'TEXT',
      text: 'TEXT',
      uuid: 'UUID',
      number: 'INTEGER',
      bigint: 'BIGINT',
      boolean: 'BOOLEAN',
      date: 'TIMESTAMP WITH TIME ZONE',
      json: 'JSONB',
    },
    mysql: {
      string: `VARCHAR(${field.maxLength || 255})`,
      text: 'TEXT',
      uuid: 'VARCHAR(36)',
      number: 'INT',
      bigint: 'BIGINT',
      boolean: 'BOOLEAN',
      date: 'TIMESTAMP',
      json: 'JSON',
    },
  };

  const t = typeof field.type === 'string' ? field.type : 'text';
  return typeMap[dialect][t] || 'TEXT';
}

function rawSqlDefault(
  field: PluginFieldAttribute,
  dialect: 'sqlite' | 'postgresql' | 'mysql',
): string | null {
  if (field.defaultValue === undefined) {
    return null;
  }
  if (field.defaultValue === 'uuid()') {
    if (dialect === 'postgresql') {
      return `gen_random_uuid()`;
    }
    // SQLite/MySQL: no built-in UUID default; omit (app generates)
    return null;
  }
  if (field.defaultValue === 'now()') {
    if (dialect === 'sqlite') {
      return `CURRENT_TIMESTAMP`;
    }
    if (dialect === 'postgresql') {
      return `NOW()`;
    }
    return `CURRENT_TIMESTAMP`;
  }
  if (typeof field.defaultValue === 'boolean') {
    if (dialect === 'sqlite') {
      return field.defaultValue ? '1' : '0';
    }
    return field.defaultValue ? 'TRUE' : 'FALSE';
  }
  if (typeof field.defaultValue === 'number') {
    return String(field.defaultValue);
  }
  if (typeof field.defaultValue === 'string') {
    return `'${field.defaultValue}'`;
  }
  return null;
}
